// Code generated by protoc-gen-goose. DO NOT EDIT.

package websocket

import (
	context "context"
	websocket "github.com/coder/websocket"
	goose "github.com/soyacen/goose"
	server "github.com/soyacen/goose/server"
	ws "github.com/soyacen/goose/ws"
	protojson "google.golang.org/protobuf/encoding/protojson"
	slog "log/slog"
	http "net/http"
	url "net/url"
)

type WebsocketStreamServer interface {
	ClientStream(ws.ClientStreamingServer[*Request, *Response]) error
	ServerStream(*Request, ws.ServerStreamingServer[*Response]) error
	BidStream(ws.BidiStreamingServer[*Request, *Response]) error
}

type WebsocketStreamClient interface {
	ClientStream(ctx context.Context) (ws.ClientStreamingClient[*Request, *Response], error)
	ServerStream(ctx context.Context, in *Request) (ws.ServerStreamingClient[*Response], error)
	BidStream(ctx context.Context) (ws.BidiStreamingClient[*Request, *Response], error)
}

func AppendWebsocketWebsocketRoute(
	router *http.ServeMux,
	service WebsocketStreamServer,
	middleware server.Middleware,
	marshalOpts protojson.MarshalOptions,
	unmarshalOpts protojson.UnmarshalOptions,
	acptOpts *websocket.AcceptOptions,
	cfg *ws.ConnConfig,
	logger *slog.Logger,
) *http.ServeMux {
	if router == nil {
		router = http.NewServeMux()
	}
	handler := &websocketStreamHandler{
		service:          service,
		middleware:       middleware,
		marshalOptions:   marshalOpts,
		unmarshalOptions: unmarshalOpts,
		acptOpts:         acptOpts,
		cfg:              cfg,
		logger:           logger,
	}
	router.Handle(_leo_goose_example_websocket_v1_Websocket_ClientStream_Desc.RouteInfo.Pattern, http.HandlerFunc(handler.ClientStream))
	router.Handle(_leo_goose_example_websocket_v1_Websocket_ServerStream_Desc.RouteInfo.Pattern, http.HandlerFunc(handler.ServerStream))
	router.Handle(_leo_goose_example_websocket_v1_Websocket_BidStream_Desc.RouteInfo.Pattern, http.HandlerFunc(handler.BidStream))
	return router
}

type websocketStreamHandler struct {
	service          WebsocketStreamServer
	middleware       server.Middleware
	marshalOptions   protojson.MarshalOptions
	unmarshalOptions protojson.UnmarshalOptions
	acptOpts         *websocket.AcceptOptions
	cfg              *ws.ConnConfig
	logger           *slog.Logger
}

func (h websocketStreamHandler) ClientStream(response http.ResponseWriter, request *http.Request) {
	invoke := func(response http.ResponseWriter, request *http.Request) {
		ctx, conn, cancel, err := ws.AcceptConn(response, request, h.acptOpts, h.cfg, h.logger)
		if err != nil {
			h.logger.Error("failed to accept websocket connection",
				"service", "Websocket", "method", "ClientStream", "error", err)
			return
		}
		defer cancel()
		stream := ws.NewServerStream[*Request, *Response](ctx, conn, h.marshalOptions, h.unmarshalOptions)
		if err := h.service.ClientStream(stream); err != nil && !ws.IsNormalClose(err) {
			h.logger.Error("failed to handle client stream",
				"service", "Websocket", "method", "ClientStream", "error", err)
		}
		if err := stream.CloseSend(); err != nil && !ws.IsNormalClose(err) {
			h.logger.Error("failed to close send stream",
				"service", "Websocket", "method", "ClientStream", "error", err)
		}
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_websocket_v1_Websocket_ClientStream_Desc.RouteInfo)
}

func (h websocketStreamHandler) ServerStream(response http.ResponseWriter, request *http.Request) {
	invoke := func(response http.ResponseWriter, request *http.Request) {
		ctx, conn, cancel, err := ws.AcceptConn(response, request, h.acptOpts, h.cfg, h.logger)
		if err != nil {
			h.logger.Error("failed to accept websocket connection",
				"service", "Websocket", "method", "ServerStream", "error", err)
			return
		}
		defer cancel()
		var req Request
		data, err := conn.Read(ctx)
		if err != nil {
			if !ws.IsNormalClose(err) {
				h.logger.Error("failed to read request",
					"service", "Websocket", "method", "ServerStream", "error", err)
			}
			return
		}
		if err := h.unmarshalOptions.Unmarshal(data, &req); err != nil {
			h.logger.Error("failed to unmarshal request",
				"service", "Websocket", "method", "ServerStream", "error", err)
			return
		}
		stream := ws.NewServerStream[*Request, *Response](ctx, conn, h.marshalOptions, h.unmarshalOptions)
		if err := h.service.ServerStream(&req, stream); err != nil && !ws.IsNormalClose(err) {
			h.logger.Error("failed to handle server stream",
				"service", "Websocket", "method", "ServerStream", "error", err)
		}
		if err := stream.CloseSend(); err != nil && !ws.IsNormalClose(err) {
			h.logger.Error("failed to close send stream",
				"service", "Websocket", "method", "ServerStream", "error", err)
		}
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_websocket_v1_Websocket_ServerStream_Desc.RouteInfo)
}

func (h websocketStreamHandler) BidStream(response http.ResponseWriter, request *http.Request) {
	invoke := func(response http.ResponseWriter, request *http.Request) {
		ctx, conn, cancel, err := ws.AcceptConn(response, request, h.acptOpts, h.cfg, h.logger)
		if err != nil {
			h.logger.Error("failed to accept websocket connection",
				"service", "Websocket", "method", "BidStream", "error", err)
			return
		}
		defer cancel()
		stream := ws.NewServerStream[*Request, *Response](ctx, conn, h.marshalOptions, h.unmarshalOptions)
		if err := h.service.BidStream(stream); err != nil && !ws.IsNormalClose(err) {
			h.logger.Error("failed to handle bidi stream",
				"service", "Websocket", "method", "BidStream", "error", err)
		}
		if err := stream.CloseSend(); err != nil && !ws.IsNormalClose(err) {
			h.logger.Error("failed to close send stream",
				"service", "Websocket", "method", "BidStream", "error", err)
		}
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_websocket_v1_Websocket_BidStream_Desc.RouteInfo)
}

var _ WebsocketStreamClient = (*websocketStreamClient)(nil)

type websocketStreamClient struct {
	url              string
	dialOpts         *websocket.DialOptions
	connCfg          *ws.ConnConfig
	logger           *slog.Logger
	marshalOptions   protojson.MarshalOptions
	unmarshalOptions protojson.UnmarshalOptions
}

func NewWebsocketStreamClient(url string,
	logger *slog.Logger,
	marshalOpts protojson.MarshalOptions,
	unmarshalOpts protojson.UnmarshalOptions,
	dialOpts *websocket.DialOptions,
) WebsocketStreamClient {
	if logger == nil {
		logger = slog.Default()
	}
	return &websocketStreamClient{
		url:              url,
		logger:           logger,
		connCfg:          ws.DefaultConnConfig(),
		marshalOptions:   marshalOpts,
		unmarshalOptions: unmarshalOpts,
		dialOpts:         dialOpts,
	}
}

func (c *websocketStreamClient) ClientStream(ctx context.Context) (ws.ClientStreamingClient[*Request, *Response], error) {
	u, err := url.JoinPath(c.url, _leo_goose_example_websocket_v1_Websocket_ClientStream_Desc.RouteInfo.Pattern)
	if err != nil {
		return nil, err
	}
	conn, err := ws.DialAndConnect(ctx, u, c.dialOpts, c.connCfg, c.logger)
	if err != nil {
		return nil, err
	}
	return ws.NewClientStreamV2[*Request, *Response](ctx, conn, c.marshalOptions, c.unmarshalOptions), nil
}

func (c *websocketStreamClient) ServerStream(ctx context.Context, in *Request) (ws.ServerStreamingClient[*Response], error) {
	u, err := url.JoinPath(c.url, _leo_goose_example_websocket_v1_Websocket_ServerStream_Desc.RouteInfo.Pattern)
	if err != nil {
		return nil, err
	}
	conn, err := ws.DialAndConnect(ctx, u, c.dialOpts, c.connCfg, c.logger)
	if err != nil {
		return nil, err
	}
	cs := ws.NewClientStreamV2[*Request, *Response](ctx, conn, c.marshalOptions, c.unmarshalOptions)
	if err := cs.SendMsg(in); err != nil {
		_ = cs.CloseSend()
		return nil, err
	}
	return cs, nil
}

func (c *websocketStreamClient) BidStream(ctx context.Context) (ws.BidiStreamingClient[*Request, *Response], error) {
	u, err := url.JoinPath(c.url, _leo_goose_example_websocket_v1_Websocket_BidStream_Desc.RouteInfo.Pattern)
	if err != nil {
		return nil, err
	}
	conn, err := ws.DialAndConnect(ctx, u, c.dialOpts, c.connCfg, c.logger)
	if err != nil {
		return nil, err
	}
	return ws.NewClientStreamV2[*Request, *Response](ctx, conn, c.marshalOptions, c.unmarshalOptions), nil
}

var _leo_goose_example_websocket_v1_Websocket_ClientStream_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "POST",
		Pattern:    "/ws/client-stream",
		FullMethod: "/leo.goose.example.websocket.v1.Websocket/ClientStream",
	},
}

var _leo_goose_example_websocket_v1_Websocket_ServerStream_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "POST",
		Pattern:    "/ws/server-stream",
		FullMethod: "/leo.goose.example.websocket.v1.Websocket/ServerStream",
	},
}

var _leo_goose_example_websocket_v1_Websocket_BidStream_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "POST",
		Pattern:    "/ws/bidi-stream",
		FullMethod: "/leo.goose.example.websocket.v1.Websocket/BidStream",
	},
}
