// Code generated by protoc-gen-goose. DO NOT EDIT.

package websocket

import (
	"context"
	"log/slog"
	"net/http"
	"sync/atomic"

	"github.com/coder/websocket"
	goose "github.com/soyacen/goose"
	"github.com/soyacen/goose/server"
	"github.com/soyacen/goose/ws"
	"google.golang.org/protobuf/encoding/protojson"
)

type StreamServiceClient interface {
	ClientStream(ctx context.Context) (ws.ClientStreamingClient[*Request, *Response], error)
	ServerStream(ctx context.Context, in *Request) (ws.ServerStreamingClient[*Response], error)
	BidStream(ctx context.Context) (ws.BidiStreamingClient[*Request, *Response], error)
}

type StreamServiceServer interface {
	ClientStream(ws.ClientStreamingServer[*Request, *Response]) error
	ServerStream(*Request, ws.ServerStreamingServer[*Response]) error
	BidStream(ws.BidiStreamingServer[*Request, *Response]) error
}

func AppendStreamServiceWebsocketRoute(router *http.ServeMux, service StreamServiceServer, cfg ws.ConnConfig, logger *slog.Logger, maxConn int64, marshalOpts protojson.MarshalOptions, unmarshalOpts protojson.UnmarshalOptions) *http.ServeMux {
	if router == nil {
		router = http.NewServeMux()
	}
	handler := &streamServiceHandler{
		service:          service,
		cfg:              cfg,
		logger:           logger,
		maxConn:          maxConn,
		marshalOptions:   marshalOpts,
		unmarshalOptions: unmarshalOpts,
	}
	router.Handle("POST /ws/client-stream", http.HandlerFunc(handler.ClientStream))
	router.Handle("POST /ws/server-stream", http.HandlerFunc(handler.ServerStream))
	router.Handle("POST /ws/bidi-stream", http.HandlerFunc(handler.BidStream))
	return router
}

type streamServiceHandler struct {
	service          StreamServiceServer
	cfg              ws.ConnConfig
	logger           *slog.Logger
	maxConn          int64
	clientActive     atomic.Int64
	serverActive     atomic.Int64
	bidiActive       atomic.Int64
	middleware       server.Middleware
	marshalOptions   protojson.MarshalOptions
	unmarshalOptions protojson.UnmarshalOptions
}

// ------------------------------------------------------------------
// 1. Client-Stream: client sends, server only receives
// ------------------------------------------------------------------

func (h *streamServiceHandler) ClientStream(response http.ResponseWriter, request *http.Request) {
	invoke := func(response http.ResponseWriter, request *http.Request) {
		if h.maxConn > 0 && h.clientActive.Load() >= h.maxConn {
			http.Error(response, "too many connections", http.StatusServiceUnavailable)
			return
		}

		wsConn, err := websocket.Accept(response, request, ws.AcceptOptions())
		if err != nil {
			h.logger.Error("websocket accept failed", slog.String("error", err.Error()))
			return
		}

		h.clientActive.Add(1)
		defer h.clientActive.Add(-1)

		conn := ws.NewConn(wsConn, h.cfg, h.logger)
		ctx, cancel := context.WithCancel(request.Context())
		defer cancel()

		go conn.Start(ctx)

		h.logger.Info("client-stream connected", slog.String("remote", request.RemoteAddr))
		defer h.logger.Info("client-stream disconnected", slog.String("remote", request.RemoteAddr))

		ss := ws.NewServerStream(ctx, conn, h.marshalOptions, h.unmarshalOptions)
		stream := ws.NewGenericServerStream[*Request, *Response](ss)
		if err := h.service.ClientStream(stream); err != nil && !ws.IsNormalClose(err) {
			h.logger.Error("client-stream error", slog.String("error", err.Error()))
		}
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_websocket_v1_ResponseBody_ClientStream_Desc.RouteInfo)
}

// ------------------------------------------------------------------
// 2. Server-Stream: server sends, client only receives
// ------------------------------------------------------------------

func (h *streamServiceHandler) ServerStream(response http.ResponseWriter, request *http.Request) {
	invoke := func(response http.ResponseWriter, request *http.Request) {
		if h.maxConn > 0 && h.serverActive.Load() >= h.maxConn {
			http.Error(response, "too many connections", http.StatusServiceUnavailable)
			return
		}

		wsConn, err := websocket.Accept(response, request, ws.AcceptOptions())
		if err != nil {
			h.logger.Error("websocket accept failed", slog.String("error", err.Error()))
			return
		}

		h.serverActive.Add(1)
		defer h.serverActive.Add(-1)

		conn := ws.NewConn(wsConn, h.cfg, h.logger)
		ctx, cancel := context.WithCancel(request.Context())
		defer cancel()

		go conn.Start(ctx)

		h.logger.Info("server-stream connected", slog.String("remote", request.RemoteAddr))
		defer h.logger.Info("server-stream disconnected", slog.String("remote", request.RemoteAddr))

		// Read the initial request from the client.
		var req Request
		data, err := conn.Read(ctx)
		if err != nil {
			if !ws.IsNormalClose(err) {
				h.logger.Error("server-stream read request error", slog.String("error", err.Error()))
			}
			return
		}
		if err := h.unmarshalOptions.Unmarshal(data, &req); err != nil {
			h.logger.Error("server-stream unmarshal error", slog.String("error", err.Error()))
			return
		}

		ss := ws.NewServerStream(ctx, conn, h.marshalOptions, h.unmarshalOptions)
		stream := ws.NewGenericServerStream[*Request, *Response](ss)
		if err := h.service.ServerStream(&req, stream); err != nil && !ws.IsNormalClose(err) {
			h.logger.Error("server-stream error", slog.String("error", err.Error()))
		}
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_websocket_v1_ResponseBody_ServerStream_Desc.RouteInfo)
}

// ------------------------------------------------------------------
// 3. Bidirectional-Stream: both sides send messages
// ------------------------------------------------------------------

func (h *streamServiceHandler) BidStream(response http.ResponseWriter, request *http.Request) {
	invoke := func(response http.ResponseWriter, request *http.Request) {
		if h.maxConn > 0 && h.bidiActive.Load() >= h.maxConn {
			http.Error(response, "too many connections", http.StatusServiceUnavailable)
			return
		}

		wsConn, err := websocket.Accept(response, request, ws.AcceptOptions())
		if err != nil {
			h.logger.Error("websocket accept failed", slog.String("error", err.Error()))
			return
		}

		h.bidiActive.Add(1)
		defer h.bidiActive.Add(-1)

		conn := ws.NewConn(wsConn, h.cfg, h.logger)
		ctx, cancel := context.WithCancel(request.Context())
		defer cancel()

		go conn.Start(ctx)

		h.logger.Info("bidi-stream connected", slog.String("remote", request.RemoteAddr))
		defer h.logger.Info("bidi-stream disconnected", slog.String("remote", request.RemoteAddr))

		ss := ws.NewServerStream(ctx, conn, h.marshalOptions, h.unmarshalOptions)
		stream := ws.NewGenericServerStream[*Request, *Response](ss)
		if err := h.service.BidStream(stream); err != nil && !ws.IsNormalClose(err) {
			h.logger.Error("bidi-stream error", slog.String("error", err.Error()))
		}
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_websocket_v1_ResponseBody_BidStream_Desc.RouteInfo)
}

var _leo_goose_example_websocket_v1_ResponseBody_ClientStream_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "POST",
		Pattern:    "/ws/client-stream",
		FullMethod: "/leo.goose.example.websocket.v1.ResponseBody/ClientStream",
	},
}

var _leo_goose_example_websocket_v1_ResponseBody_ServerStream_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "POST",
		Pattern:    "/ws/server-stream",
		FullMethod: "/leo.goose.example.websocket.v1.ResponseBody/ServerStream",
	},
}

var _leo_goose_example_websocket_v1_ResponseBody_BidStream_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "POST",
		Pattern:    "/ws/bidi-stream",
		FullMethod: "/leo.goose.example.websocket.v1.ResponseBody/BidStream",
	},
}

// ---------------------------------------------------------------------------
// streamServiceClient — implements StreamServiceClient
// ---------------------------------------------------------------------------

// Compile-time check: streamServiceClient implements StreamServiceClient.
var _ StreamServiceClient = (*streamServiceClient)(nil)

// streamServiceClient implements the StreamServiceClient interface by creating
// WebSocket connections for each RPC call. This is what protoc-gen-goose
// would generate as the client stub.
type streamServiceClient struct {
	url              string
	dialOpts         *websocket.DialOptions
	connCfg          ws.ConnConfig
	logger           *slog.Logger
	marshalOptions   protojson.MarshalOptions
	unmarshalOptions protojson.UnmarshalOptions
}

// NewStreamServiceClient creates a client that implements StreamServiceClient.
// url is the WebSocket endpoint (e.g., "ws://localhost:8080/ws/bidi-stream").
// Each method call dials a new connection for the corresponding streaming RPC.
func NewStreamServiceClient(url string, logger *slog.Logger, marshalOpts protojson.MarshalOptions, unmarshalOpts protojson.UnmarshalOptions) StreamServiceClient {
	if logger == nil {
		logger = slog.Default()
	}
	return &streamServiceClient{
		url:              url,
		logger:           logger,
		connCfg:          ws.DefaultConnConfig(),
		marshalOptions:   marshalOpts,
		unmarshalOptions: unmarshalOpts,
		dialOpts: &websocket.DialOptions{
			CompressionMode: websocket.CompressionContextTakeover,
		},
	}
}

// dialAndConnect dials the WebSocket endpoint and returns a ClientStream ready
// for use. The caller is responsible for the returned cancel function if the
// stream is not fully consumed.
func (c *streamServiceClient) dialAndConnect(ctx context.Context) (ws.ClientStream, error) {
	wsConn, _, err := websocket.Dial(ctx, c.url, c.dialOpts)
	if err != nil {
		return nil, err
	}

	conn := ws.NewConn(wsConn, c.connCfg, c.logger)
	go conn.Start(ctx)

	return ws.NewClientStream(ctx, conn, c.marshalOptions, c.unmarshalOptions), nil
}

// ClientStream opens a client-streaming RPC.
func (c *streamServiceClient) ClientStream(ctx context.Context) (ws.ClientStreamingClient[*Request, *Response], error) {
	cs, err := c.dialAndConnect(ctx)
	if err != nil {
		return nil, err
	}
	return ws.NewGenericClientStream[*Request, *Response](cs), nil
}

// ServerStream opens a server-streaming RPC. It sends the initial request
// and returns a stream for receiving multiple responses.
func (c *streamServiceClient) ServerStream(ctx context.Context, in *Request) (ws.ServerStreamingClient[*Response], error) {
	cs, err := c.dialAndConnect(ctx)
	if err != nil {
		return nil, err
	}

	// Send the initial request.
	if err := cs.SendMsg(in); err != nil {
		_ = cs.CloseSend()
		return nil, err
	}

	return ws.NewGenericClientStream[*Request, *Response](cs), nil
}

// Bid opens a bidirectional-streaming RPC.
func (c *streamServiceClient) BidStream(ctx context.Context) (ws.BidiStreamingClient[*Request, *Response], error) {
	cs, err := c.dialAndConnect(ctx)
	if err != nil {
		return nil, err
	}
	return ws.NewGenericClientStream[*Request, *Response](cs), nil
}
