// Code generated by protoc-gen-goose. DO NOT EDIT.

package websocket

import (
	"context"
	"log/slog"
	"net/http"
	"net/url"

	"github.com/coder/websocket"
	goose "github.com/soyacen/goose"
	"github.com/soyacen/goose/server"
	"github.com/soyacen/goose/ws"
	"google.golang.org/protobuf/encoding/protojson"
)

type StreamServiceStreamClient interface {
	ClientStream(ctx context.Context) (ws.ClientStreamingClient[*Request, *Response], error)
	ServerStream(ctx context.Context, in *Request) (ws.ServerStreamingClient[*Response], error)
	BidStream(ctx context.Context) (ws.BidiStreamingClient[*Request, *Response], error)
}

type StreamServiceStreamServer interface {
	ClientStream(ws.ClientStreamingServer[*Request, *Response]) error
	ServerStream(*Request, ws.ServerStreamingServer[*Response]) error
	BidStream(ws.BidiStreamingServer[*Request, *Response]) error
}

func AppendStreamServiceWebsocketRoute(router *http.ServeMux, service StreamServiceStreamServer, errorEncoder goose.ErrorEncoder, cfg ws.ConnConfig, logger *slog.Logger, maxConn int64, marshalOpts protojson.MarshalOptions, unmarshalOpts protojson.UnmarshalOptions) *http.ServeMux {
	if router == nil {
		router = http.NewServeMux()
	}
	handler := &streamServiceHandler{
		service:          service,
		errorEncoder:     errorEncoder,
		cfg:              cfg,
		logger:           logger,
		marshalOptions:   marshalOpts,
		unmarshalOptions: unmarshalOpts,
	}
	router.Handle(_leo_goose_example_websocket_v1_ResponseBody_ClientStream_Desc.RouteInfo.Pattern, http.HandlerFunc(handler.ClientStream))
	router.Handle(_leo_goose_example_websocket_v1_ResponseBody_ServerStream_Desc.RouteInfo.Pattern, http.HandlerFunc(handler.ServerStream))
	router.Handle(_leo_goose_example_websocket_v1_ResponseBody_BidStream_Desc.RouteInfo.Pattern, http.HandlerFunc(handler.BidStream))
	return router
}

type streamServiceHandler struct {
	service          StreamServiceStreamServer
	errorEncoder     goose.ErrorEncoder
	cfg              ws.ConnConfig
	logger           *slog.Logger
	middleware       server.Middleware
	marshalOptions   protojson.MarshalOptions
	unmarshalOptions protojson.UnmarshalOptions
}

// ------------------------------------------------------------------
// 1. Client-Stream: client sends, server only receives
// ------------------------------------------------------------------

func (h *streamServiceHandler) ClientStream(response http.ResponseWriter, request *http.Request) {
	invoke := func(response http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		wsConn, err := websocket.Accept(response, request, ws.AcceptOptions())
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}

		conn := ws.NewConn(wsConn, h.cfg, h.logger)
		ctx, cancel := context.WithCancel(ctx)
		defer cancel()

		go conn.Start(context.Background())

		ss := ws.NewServerStream(ctx, conn, h.marshalOptions, h.unmarshalOptions)
		stream := ws.NewGenericServerStream[*Request, *Response](ss)
		if err := h.service.ClientStream(stream); err != nil && !ws.IsNormalClose(err) {
			h.errorEncoder(ctx, err, response)
		}
		// Ensure pending writes are drained and the WebSocket is closed
		// after the handler returns, even if it didn't call SendAndClose.
		_ = stream.CloseSend()
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_websocket_v1_ResponseBody_ClientStream_Desc.RouteInfo)
}

// ------------------------------------------------------------------
// 2. Server-Stream: server sends, client only receives
// ------------------------------------------------------------------

func (h *streamServiceHandler) ServerStream(response http.ResponseWriter, request *http.Request) {
	invoke := func(response http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		wsConn, err := websocket.Accept(response, request, ws.AcceptOptions())
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}

		conn := ws.NewConn(wsConn, h.cfg, h.logger)
		ctx, cancel := context.WithCancel(ctx)
		defer cancel()

		go conn.Start(context.Background())

		// Read the initial request from the client.
		var req Request
		data, err := conn.Read(ctx)
		if err != nil {
			if !ws.IsNormalClose(err) {
				h.errorEncoder(ctx, err, response)
			}
			return
		}
		if err := h.unmarshalOptions.Unmarshal(data, &req); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}

		ss := ws.NewServerStream(ctx, conn, h.marshalOptions, h.unmarshalOptions)
		stream := ws.NewGenericServerStream[*Request, *Response](ss)
		if err := h.service.ServerStream(&req, stream); err != nil && !ws.IsNormalClose(err) {
			h.errorEncoder(ctx, err, response)
		}
		// Ensure pending writes are drained and the WebSocket is closed
		// after the handler returns, even if it didn't call CloseSend.
		_ = stream.CloseSend()
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_websocket_v1_ResponseBody_ServerStream_Desc.RouteInfo)
}

// ------------------------------------------------------------------
// 3. Bidirectional-Stream: both sides send messages
// ------------------------------------------------------------------

func (h *streamServiceHandler) BidStream(response http.ResponseWriter, request *http.Request) {
	invoke := func(response http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		wsConn, err := websocket.Accept(response, request, ws.AcceptOptions())
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}

		conn := ws.NewConn(wsConn, h.cfg, h.logger)
		ctx, cancel := context.WithCancel(ctx)
		defer cancel()

		go conn.Start(context.Background())

		ss := ws.NewServerStream(ctx, conn, h.marshalOptions, h.unmarshalOptions)
		stream := ws.NewGenericServerStream[*Request, *Response](ss)
		if err := h.service.BidStream(stream); err != nil && !ws.IsNormalClose(err) {
			h.errorEncoder(ctx, err, response)
		}
		// Ensure pending writes are drained and the WebSocket is closed
		// after the handler returns, even if it didn't call CloseSend.
		_ = stream.CloseSend()
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_websocket_v1_ResponseBody_BidStream_Desc.RouteInfo)
}

// ---------------------------------------------------------------------------
// streamServiceClient — implements StreamServiceClient
// ---------------------------------------------------------------------------

// Compile-time check: streamServiceClient implements StreamServiceClient.
var _ StreamServiceStreamClient = (*streamServiceClient)(nil)

// streamServiceClient implements the StreamServiceClient interface by creating
// WebSocket connections for each RPC call. This is what protoc-gen-goose
// would generate as the client stub.
type streamServiceClient struct {
	url              string
	dialOpts         *websocket.DialOptions
	connCfg          ws.ConnConfig
	logger           *slog.Logger
	marshalOptions   protojson.MarshalOptions
	unmarshalOptions protojson.UnmarshalOptions
}

// NewStreamServiceClient creates a client that implements StreamServiceClient.
// url is the WebSocket endpoint (e.g., "ws://localhost:8080/ws/bidi-stream").
// Each method call dials a new connection for the corresponding streaming RPC.
func NewStreamServiceClient(url string, logger *slog.Logger, marshalOpts protojson.MarshalOptions, unmarshalOpts protojson.UnmarshalOptions) StreamServiceStreamClient {
	if logger == nil {
		logger = slog.Default()
	}
	return &streamServiceClient{
		url:              url,
		logger:           logger,
		connCfg:          ws.DefaultConnConfig(),
		marshalOptions:   marshalOpts,
		unmarshalOptions: unmarshalOpts,
		dialOpts: &websocket.DialOptions{
			CompressionMode: websocket.CompressionContextTakeover,
		},
	}
}

// dialAndConnect dials the WebSocket endpoint and returns a ClientStream ready
// for use. The caller is responsible for the returned cancel function if the
// stream is not fully consumed.
func (c *streamServiceClient) dialAndConnect(ctx context.Context, path string) (ws.ClientStream, error) {
	u, err := url.JoinPath(c.url, path)
	if err != nil {
		return nil, err
	}

	wsConn, _, err := websocket.Dial(ctx, u, c.dialOpts)
	if err != nil {
		return nil, err
	}

	conn := ws.NewConn(wsConn, c.connCfg, c.logger)
	// NewClientStream starts conn.Start internally.
	return ws.NewClientStream(ctx, conn, c.marshalOptions, c.unmarshalOptions), nil
}

// ClientStream opens a client-streaming RPC.
func (c *streamServiceClient) ClientStream(ctx context.Context) (ws.ClientStreamingClient[*Request, *Response], error) {
	cs, err := c.dialAndConnect(ctx, _leo_goose_example_websocket_v1_ResponseBody_ClientStream_Desc.RouteInfo.Pattern)
	if err != nil {
		return nil, err
	}
	return ws.NewGenericClientStream[*Request, *Response](cs), nil
}

// ServerStream opens a server-streaming RPC. It sends the initial request
// and returns a stream for receiving multiple responses.
func (c *streamServiceClient) ServerStream(ctx context.Context, in *Request) (ws.ServerStreamingClient[*Response], error) {
	cs, err := c.dialAndConnect(ctx, _leo_goose_example_websocket_v1_ResponseBody_ServerStream_Desc.RouteInfo.Pattern)
	if err != nil {
		return nil, err
	}

	// Send the initial request.
	if err := cs.SendMsg(in); err != nil {
		_ = cs.CloseSend()
		return nil, err
	}

	return ws.NewGenericClientStream[*Request, *Response](cs), nil
}

// Bid opens a bidirectional-streaming RPC.
func (c *streamServiceClient) BidStream(ctx context.Context) (ws.BidiStreamingClient[*Request, *Response], error) {
	cs, err := c.dialAndConnect(ctx, _leo_goose_example_websocket_v1_ResponseBody_BidStream_Desc.RouteInfo.Pattern)
	if err != nil {
		return nil, err
	}
	return ws.NewGenericClientStream[*Request, *Response](cs), nil
}

var _leo_goose_example_websocket_v1_ResponseBody_ClientStream_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "POST",
		Pattern:    "/ws/client-stream",
		FullMethod: "/leo.goose.example.websocket.v1.ResponseBody/ClientStream",
	},
}

var _leo_goose_example_websocket_v1_ResponseBody_ServerStream_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "POST",
		Pattern:    "/ws/server-stream",
		FullMethod: "/leo.goose.example.websocket.v1.ResponseBody/ServerStream",
	},
}

var _leo_goose_example_websocket_v1_ResponseBody_BidStream_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "POST",
		Pattern:    "/ws/bidi-stream",
		FullMethod: "/leo.goose.example.websocket.v1.ResponseBody/BidStream",
	},
}
