// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: example/upload/upload.proto

package upload

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	http "google.golang.org/genproto/googleapis/rpc/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadEmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *httpbody.HttpBody     `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadEmbedRequest) Reset() {
	*x = UploadEmbedRequest{}
	mi := &file_example_upload_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadEmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadEmbedRequest) ProtoMessage() {}

func (x *UploadEmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_upload_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadEmbedRequest.ProtoReflect.Descriptor instead.
func (*UploadEmbedRequest) Descriptor() ([]byte, []int) {
	return file_example_upload_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadEmbedRequest) GetBody() *httpbody.HttpBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_example_upload_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_example_upload_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_example_upload_upload_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_example_upload_upload_proto protoreflect.FileDescriptor

const file_example_upload_upload_proto_rawDesc = "" +
	"\n" +
	"\x1bexample/upload/upload.proto\x12\x1bleo.goose.example.upload.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/httpbody.proto\x1a\x15google/rpc/http.proto\">\n" +
	"\x12UploadEmbedRequest\x12(\n" +
	"\x04body\x18\x01 \x01(\v2\x14.google.api.HttpBodyR\x04body\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xdc\x02\n" +
	"\x06Upload\x12`\n" +
	"\x06Upload\x12\x14.google.api.HttpBody\x1a%.leo.goose.example.upload.v1.Response\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/upload/api\x12\x84\x01\n" +
	"\vUploadEmbed\x12/.leo.goose.example.upload.v1.UploadEmbedRequest\x1a%.leo.goose.example.upload.v1.Response\"\x1d\x82\xd3\xe4\x93\x02\x17:\x04body\x1a\x0f/v1/upload/embd\x12i\n" +
	"\fUploadForRPC\x12\x17.google.rpc.HttpRequest\x1a%.leo.goose.example.upload.v1.Response\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/upload/rpcB3Z1github.com/soyacen/goose/example/upload/v1;uploadb\x06proto3"

var (
	file_example_upload_upload_proto_rawDescOnce sync.Once
	file_example_upload_upload_proto_rawDescData []byte
)

func file_example_upload_upload_proto_rawDescGZIP() []byte {
	file_example_upload_upload_proto_rawDescOnce.Do(func() {
		file_example_upload_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_upload_upload_proto_rawDesc), len(file_example_upload_upload_proto_rawDesc)))
	})
	return file_example_upload_upload_proto_rawDescData
}

var file_example_upload_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_example_upload_upload_proto_goTypes = []any{
	(*UploadEmbedRequest)(nil), // 0: leo.goose.example.upload.v1.UploadEmbedRequest
	(*Response)(nil),           // 1: leo.goose.example.upload.v1.Response
	(*httpbody.HttpBody)(nil),  // 2: google.api.HttpBody
	(*http.HttpRequest)(nil),   // 3: google.rpc.HttpRequest
}
var file_example_upload_upload_proto_depIdxs = []int32{
	2, // 0: leo.goose.example.upload.v1.UploadEmbedRequest.body:type_name -> google.api.HttpBody
	2, // 1: leo.goose.example.upload.v1.Upload.Upload:input_type -> google.api.HttpBody
	0, // 2: leo.goose.example.upload.v1.Upload.UploadEmbed:input_type -> leo.goose.example.upload.v1.UploadEmbedRequest
	3, // 3: leo.goose.example.upload.v1.Upload.UploadForRPC:input_type -> google.rpc.HttpRequest
	1, // 4: leo.goose.example.upload.v1.Upload.Upload:output_type -> leo.goose.example.upload.v1.Response
	1, // 5: leo.goose.example.upload.v1.Upload.UploadEmbed:output_type -> leo.goose.example.upload.v1.Response
	1, // 6: leo.goose.example.upload.v1.Upload.UploadForRPC:output_type -> leo.goose.example.upload.v1.Response
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_example_upload_upload_proto_init() }
func file_example_upload_upload_proto_init() {
	if File_example_upload_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_upload_upload_proto_rawDesc), len(file_example_upload_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_upload_upload_proto_goTypes,
		DependencyIndexes: file_example_upload_upload_proto_depIdxs,
		MessageInfos:      file_example_upload_upload_proto_msgTypes,
	}.Build()
	File_example_upload_upload_proto = out.File
	file_example_upload_upload_proto_goTypes = nil
	file_example_upload_upload_proto_depIdxs = nil
}
