// Code generated by protoc-gen-goose. DO NOT EDIT.

package upload

import (
	bytes "bytes"
	context "context"
	errors "errors"
	goose "github.com/soyacen/goose"
	client "github.com/soyacen/goose/client"
	resolver "github.com/soyacen/goose/client/resolver"
	server "github.com/soyacen/goose/server"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	http "google.golang.org/genproto/googleapis/rpc/http"
	protojson "google.golang.org/protobuf/encoding/protojson"
	http1 "net/http"
)

type UploadService interface {
	Upload(ctx context.Context, req *httpbody.HttpBody) (*Response, error)
	UploadEmbed(ctx context.Context, req *UploadEmbedRequest) (*Response, error)
	UploadForRPC(ctx context.Context, req *http.HttpRequest) (*Response, error)
}

func AppendUploadHttpRoute(router *http1.ServeMux, service UploadService, opts ...server.Option) *http1.ServeMux {
	if router == nil {
		router = http1.NewServeMux()
	}
	options := server.NewOptions(opts...)
	handler := uploadHandler{
		service: service,
		decoder: uploadRequestDecoder{
			unmarshalOptions: options.UnmarshalOptions(),
		},
		encoder: uploadResponseEncoder{
			marshalOptions:   options.MarshalOptions(),
			unmarshalOptions: options.UnmarshalOptions(),
		},
		errorEncoder:            options.ErrorEncoder(),
		shouldFailFast:          options.ShouldFailFast(),
		onValidationErrCallback: options.OnValidationErrCallback(),
		middleware:              server.Chain(options.Middlewares()...),
	}
	router.Handle("PUT /v1/upload/api", http1.HandlerFunc(handler.Upload))
	router.Handle("PUT /v1/upload/embd", http1.HandlerFunc(handler.UploadEmbed))
	router.Handle("PUT /v1/upload/rpc", http1.HandlerFunc(handler.UploadForRPC))
	return router
}

type uploadHandler struct {
	service                 UploadService
	decoder                 uploadRequestDecoder
	encoder                 uploadResponseEncoder
	errorEncoder            goose.ErrorEncoder
	shouldFailFast          bool
	onValidationErrCallback goose.OnValidationErrCallback
	middleware              server.Middleware
}

func (h uploadHandler) Upload(response http1.ResponseWriter, request *http1.Request) {
	invoke := func(response http1.ResponseWriter, request *http1.Request) {
		ctx := request.Context()
		req, err := h.decoder.Upload(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := goose.ValidateRequest(ctx, req, h.shouldFailFast, h.onValidationErrCallback); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		resp, err := h.service.Upload(ctx, req)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := h.encoder.Upload(ctx, response, resp); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_upload_v1_Upload_Upload_Desc.RouteInfo)
}

func (h uploadHandler) UploadEmbed(response http1.ResponseWriter, request *http1.Request) {
	invoke := func(response http1.ResponseWriter, request *http1.Request) {
		ctx := request.Context()
		req, err := h.decoder.UploadEmbed(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := goose.ValidateRequest(ctx, req, h.shouldFailFast, h.onValidationErrCallback); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		resp, err := h.service.UploadEmbed(ctx, req)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := h.encoder.UploadEmbed(ctx, response, resp); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_upload_v1_Upload_UploadEmbed_Desc.RouteInfo)
}

func (h uploadHandler) UploadForRPC(response http1.ResponseWriter, request *http1.Request) {
	invoke := func(response http1.ResponseWriter, request *http1.Request) {
		ctx := request.Context()
		req, err := h.decoder.UploadForRPC(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := goose.ValidateRequest(ctx, req, h.shouldFailFast, h.onValidationErrCallback); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		resp, err := h.service.UploadForRPC(ctx, req)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := h.encoder.UploadForRPC(ctx, response, resp); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_upload_v1_Upload_UploadForRPC_Desc.RouteInfo)
}

type uploadRequestDecoder struct {
	unmarshalOptions protojson.UnmarshalOptions
}

func (decoder uploadRequestDecoder) Upload(ctx context.Context, request *http1.Request) (*httpbody.HttpBody, error) {
	req := &httpbody.HttpBody{}
	ok, err := server.CustomDecodeRequest(ctx, request, req)
	if err != nil {
		return nil, err
	}
	if ok {
		return req, nil
	}
	if err := server.DecodeHttpBody(ctx, request, req); err != nil {
		return nil, err
	}
	return req, nil
}
func (decoder uploadRequestDecoder) UploadEmbed(ctx context.Context, request *http1.Request) (*UploadEmbedRequest, error) {
	req := &UploadEmbedRequest{}
	ok, err := server.CustomDecodeRequest(ctx, request, req)
	if err != nil {
		return nil, err
	}
	if ok {
		return req, nil
	}
	if req.Body == nil {
		req.Body = &httpbody.HttpBody{}
	}
	if err := server.DecodeHttpBody(ctx, request, req.Body); err != nil {
		return nil, err
	}
	return req, nil
}
func (decoder uploadRequestDecoder) UploadForRPC(ctx context.Context, request *http1.Request) (*http.HttpRequest, error) {
	req := &http.HttpRequest{}
	ok, err := server.CustomDecodeRequest(ctx, request, req)
	if err != nil {
		return nil, err
	}
	if ok {
		return req, nil
	}
	if err := server.DecodeHttpRequest(ctx, request, req); err != nil {
		return nil, err
	}
	return req, nil
}

type uploadResponseEncoder struct {
	marshalOptions   protojson.MarshalOptions
	unmarshalOptions protojson.UnmarshalOptions
}

func (encoder uploadResponseEncoder) Upload(ctx context.Context, w http1.ResponseWriter, resp *Response) error {
	return server.EncodeResponse(ctx, w, resp, encoder.marshalOptions)
}
func (encoder uploadResponseEncoder) UploadEmbed(ctx context.Context, w http1.ResponseWriter, resp *Response) error {
	return server.EncodeResponse(ctx, w, resp, encoder.marshalOptions)
}
func (encoder uploadResponseEncoder) UploadForRPC(ctx context.Context, w http1.ResponseWriter, resp *Response) error {
	return server.EncodeResponse(ctx, w, resp, encoder.marshalOptions)
}

func NewUploadHttpClient(target string, opts ...client.Option) UploadService {
	options := client.NewOptions(opts...)
	client := &uploadHttpClient{
		client: options.Client(),
		encoder: uploadRequestEncoder{
			target:         target,
			marshalOptions: options.MarshalOptions(),
			resolver:       options.Resolver(),
		},
		decoder: uploadResponseDecoder{
			unmarshalOptions: options.UnmarshalOptions(),
			errorDecoder:     options.ErrorDecoder(),
			errorFactory:     options.ErrorFactory(),
		},
		shouldFailFast:          options.ShouldFailFast(),
		onValidationErrCallback: options.OnValidationErrCallback(),
		middleware:              client.Chain(options.Middlewares()...),
	}
	return client
}

type uploadHttpClient struct {
	client                  *http1.Client
	encoder                 uploadRequestEncoder
	decoder                 uploadResponseDecoder
	shouldFailFast          bool
	onValidationErrCallback goose.OnValidationErrCallback
	middleware              client.Middleware
}

func (c *uploadHttpClient) Upload(ctx context.Context, req *httpbody.HttpBody) (*Response, error) {
	if err := goose.ValidateRequest(ctx, req, c.shouldFailFast, c.onValidationErrCallback); err != nil {
		return nil, err
	}
	request, err := c.encoder.Upload(ctx, req)
	if err != nil {
		return nil, err
	}
	response, err := client.Invoke(c.middleware, c.client, request, _leo_goose_example_upload_v1_Upload_Upload_Desc.RouteInfo)
	if err != nil {
		return nil, err
	}
	resp, err := c.decoder.Upload(ctx, response)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *uploadHttpClient) UploadEmbed(ctx context.Context, req *UploadEmbedRequest) (*Response, error) {
	if err := goose.ValidateRequest(ctx, req, c.shouldFailFast, c.onValidationErrCallback); err != nil {
		return nil, err
	}
	request, err := c.encoder.UploadEmbed(ctx, req)
	if err != nil {
		return nil, err
	}
	response, err := client.Invoke(c.middleware, c.client, request, _leo_goose_example_upload_v1_Upload_UploadEmbed_Desc.RouteInfo)
	if err != nil {
		return nil, err
	}
	resp, err := c.decoder.UploadEmbed(ctx, response)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *uploadHttpClient) UploadForRPC(ctx context.Context, req *http.HttpRequest) (*Response, error) {
	if err := goose.ValidateRequest(ctx, req, c.shouldFailFast, c.onValidationErrCallback); err != nil {
		return nil, err
	}
	request, err := c.encoder.UploadForRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	response, err := client.Invoke(c.middleware, c.client, request, _leo_goose_example_upload_v1_Upload_UploadForRPC_Desc.RouteInfo)
	if err != nil {
		return nil, err
	}
	resp, err := c.decoder.UploadForRPC(ctx, response)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

type uploadRequestEncoder struct {
	target         string
	marshalOptions protojson.MarshalOptions
	resolver       resolver.Resolver
}

func (encoder *uploadRequestEncoder) Upload(ctx context.Context, req *httpbody.HttpBody) (*http1.Request, error) {
	if req == nil {
		return nil, errors.New("request is nil")
	}
	target, err := resolver.Resolve(ctx, encoder.resolver, encoder.target)
	if err != nil {
		return nil, err
	}
	method := "PUT"
	header := http1.Header{}
	var body bytes.Buffer
	if err := client.EncodeHttpBody(ctx, req, header, &body); err != nil {
		return nil, err
	}
	path := "/v1/upload/api"
	target.Path = path
	request, err := http1.NewRequestWithContext(ctx, method, target.String(), &body)
	if err != nil {
		return nil, err
	}
	goose.CopyHeader(request.Header, header)
	return request, nil
}

func (encoder *uploadRequestEncoder) UploadEmbed(ctx context.Context, req *UploadEmbedRequest) (*http1.Request, error) {
	if req == nil {
		return nil, errors.New("request is nil")
	}
	target, err := resolver.Resolve(ctx, encoder.resolver, encoder.target)
	if err != nil {
		return nil, err
	}
	method := "PUT"
	header := http1.Header{}
	var body bytes.Buffer
	if err := client.EncodeHttpBody(ctx, req.GetBody(), header, &body); err != nil {
		return nil, err
	}
	path := "/v1/upload/embd"
	target.Path = path
	request, err := http1.NewRequestWithContext(ctx, method, target.String(), &body)
	if err != nil {
		return nil, err
	}
	goose.CopyHeader(request.Header, header)
	return request, nil
}

func (encoder *uploadRequestEncoder) UploadForRPC(ctx context.Context, req *http.HttpRequest) (*http1.Request, error) {
	if req == nil {
		return nil, errors.New("request is nil")
	}
	target, err := resolver.Resolve(ctx, encoder.resolver, encoder.target)
	if err != nil {
		return nil, err
	}
	method := "PUT"
	header := http1.Header{}
	var body bytes.Buffer
	if err := client.EncodeHttpRequest(ctx, req, header, &body); err != nil {
		return nil, err
	}
	path := "/v1/upload/rpc"
	target.Path = path
	request, err := http1.NewRequestWithContext(ctx, method, target.String(), &body)
	if err != nil {
		return nil, err
	}
	goose.CopyHeader(request.Header, header)
	return request, nil
}

type uploadResponseDecoder struct {
	unmarshalOptions protojson.UnmarshalOptions
	errorDecoder     goose.ErrorDecoder
	errorFactory     goose.ErrorFactory
}

func (decoder *uploadResponseDecoder) Upload(ctx context.Context, response *http1.Response) (*Response, error) {
	if respErr, ok := decoder.errorDecoder(ctx, response, decoder.errorFactory); ok {
		return nil, respErr
	}
	resp := &Response{}
	if err := client.DecodeMessage(ctx, response, resp, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	return resp, nil
}

func (decoder *uploadResponseDecoder) UploadEmbed(ctx context.Context, response *http1.Response) (*Response, error) {
	if respErr, ok := decoder.errorDecoder(ctx, response, decoder.errorFactory); ok {
		return nil, respErr
	}
	resp := &Response{}
	if err := client.DecodeMessage(ctx, response, resp, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	return resp, nil
}

func (decoder *uploadResponseDecoder) UploadForRPC(ctx context.Context, response *http1.Response) (*Response, error) {
	if respErr, ok := decoder.errorDecoder(ctx, response, decoder.errorFactory); ok {
		return nil, respErr
	}
	resp := &Response{}
	if err := client.DecodeMessage(ctx, response, resp, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	return resp, nil
}

var _leo_goose_example_upload_v1_Upload_Upload_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "PUT",
		Pattern:    "/v1/upload/api",
		FullMethod: "/leo.goose.example.upload.v1.Upload/Upload",
	},
}

var _leo_goose_example_upload_v1_Upload_UploadEmbed_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "PUT",
		Pattern:    "/v1/upload/embd",
		FullMethod: "/leo.goose.example.upload.v1.Upload/UploadEmbed",
	},
}

var _leo_goose_example_upload_v1_Upload_UploadForRPC_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "PUT",
		Pattern:    "/v1/upload/rpc",
		FullMethod: "/leo.goose.example.upload.v1.Upload/UploadForRPC",
	},
}
