// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: example/path/path.proto

package path

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumPathRequest_Status int32

const (
	EnumPathRequest_UNKNOWN       EnumPathRequest_Status = 0
	EnumPathRequest_OK            EnumPathRequest_Status = 1
	EnumPathRequest_CANCELLED     EnumPathRequest_Status = 2
	EnumPathRequest_UNKNOWN_ERROR EnumPathRequest_Status = 3
)

// Enum value maps for EnumPathRequest_Status.
var (
	EnumPathRequest_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "OK",
		2: "CANCELLED",
		3: "UNKNOWN_ERROR",
	}
	EnumPathRequest_Status_value = map[string]int32{
		"UNKNOWN":       0,
		"OK":            1,
		"CANCELLED":     2,
		"UNKNOWN_ERROR": 3,
	}
)

func (x EnumPathRequest_Status) Enum() *EnumPathRequest_Status {
	p := new(EnumPathRequest_Status)
	*p = x
	return p
}

func (x EnumPathRequest_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumPathRequest_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_example_path_path_proto_enumTypes[0].Descriptor()
}

func (EnumPathRequest_Status) Type() protoreflect.EnumType {
	return &file_example_path_path_proto_enumTypes[0]
}

func (x EnumPathRequest_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumPathRequest_Status.Descriptor instead.
func (EnumPathRequest_Status) EnumDescriptor() ([]byte, []int) {
	return file_example_path_path_proto_rawDescGZIP(), []int{8, 0}
}

type BoolPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bool          bool                   `protobuf:"varint,1,opt,name=bool,proto3" json:"bool,omitempty"`
	OptBool       *bool                  `protobuf:"varint,2,opt,name=opt_bool,json=optBool,proto3,oneof" json:"opt_bool,omitempty"`
	WrapBool      *wrapperspb.BoolValue  `protobuf:"bytes,3,opt,name=wrap_bool,json=wrapBool,proto3" json:"wrap_bool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolPathRequest) Reset() {
	*x = BoolPathRequest{}
	mi := &file_example_path_path_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolPathRequest) ProtoMessage() {}

func (x *BoolPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_path_path_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolPathRequest.ProtoReflect.Descriptor instead.
func (*BoolPathRequest) Descriptor() ([]byte, []int) {
	return file_example_path_path_proto_rawDescGZIP(), []int{0}
}

func (x *BoolPathRequest) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *BoolPathRequest) GetOptBool() bool {
	if x != nil && x.OptBool != nil {
		return *x.OptBool
	}
	return false
}

func (x *BoolPathRequest) GetWrapBool() *wrapperspb.BoolValue {
	if x != nil {
		return x.WrapBool
	}
	return nil
}

type Int32PathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int32         int32                  `protobuf:"varint,1,opt,name=int32,proto3" json:"int32,omitempty"`
	Sint32        int32                  `protobuf:"zigzag32,2,opt,name=sint32,proto3" json:"sint32,omitempty"`
	Sfixed32      int32                  `protobuf:"fixed32,3,opt,name=sfixed32,proto3" json:"sfixed32,omitempty"`
	OptInt32      *int32                 `protobuf:"varint,4,opt,name=opt_int32,json=optInt32,proto3,oneof" json:"opt_int32,omitempty"`
	OptSint32     *int32                 `protobuf:"zigzag32,5,opt,name=opt_sint32,json=optSint32,proto3,oneof" json:"opt_sint32,omitempty"`
	OptSfixed32   *int32                 `protobuf:"fixed32,6,opt,name=opt_sfixed32,json=optSfixed32,proto3,oneof" json:"opt_sfixed32,omitempty"`
	WrapInt32     *wrapperspb.Int32Value `protobuf:"bytes,7,opt,name=wrap_int32,json=wrapInt32,proto3" json:"wrap_int32,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int32PathRequest) Reset() {
	*x = Int32PathRequest{}
	mi := &file_example_path_path_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32PathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32PathRequest) ProtoMessage() {}

func (x *Int32PathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_path_path_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32PathRequest.ProtoReflect.Descriptor instead.
func (*Int32PathRequest) Descriptor() ([]byte, []int) {
	return file_example_path_path_proto_rawDescGZIP(), []int{1}
}

func (x *Int32PathRequest) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *Int32PathRequest) GetSint32() int32 {
	if x != nil {
		return x.Sint32
	}
	return 0
}

func (x *Int32PathRequest) GetSfixed32() int32 {
	if x != nil {
		return x.Sfixed32
	}
	return 0
}

func (x *Int32PathRequest) GetOptInt32() int32 {
	if x != nil && x.OptInt32 != nil {
		return *x.OptInt32
	}
	return 0
}

func (x *Int32PathRequest) GetOptSint32() int32 {
	if x != nil && x.OptSint32 != nil {
		return *x.OptSint32
	}
	return 0
}

func (x *Int32PathRequest) GetOptSfixed32() int32 {
	if x != nil && x.OptSfixed32 != nil {
		return *x.OptSfixed32
	}
	return 0
}

func (x *Int32PathRequest) GetWrapInt32() *wrapperspb.Int32Value {
	if x != nil {
		return x.WrapInt32
	}
	return nil
}

type Int64PathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int64         int64                  `protobuf:"varint,1,opt,name=int64,proto3" json:"int64,omitempty"`
	Sint64        int64                  `protobuf:"zigzag64,2,opt,name=sint64,proto3" json:"sint64,omitempty"`
	Sfixed64      int64                  `protobuf:"fixed64,3,opt,name=sfixed64,proto3" json:"sfixed64,omitempty"`
	OptInt64      *int64                 `protobuf:"varint,4,opt,name=opt_int64,json=optInt64,proto3,oneof" json:"opt_int64,omitempty"`
	OptSint64     *int64                 `protobuf:"zigzag64,5,opt,name=opt_sint64,json=optSint64,proto3,oneof" json:"opt_sint64,omitempty"`
	OptSfixed64   *int64                 `protobuf:"fixed64,6,opt,name=opt_sfixed64,json=optSfixed64,proto3,oneof" json:"opt_sfixed64,omitempty"`
	WrapInt64     *wrapperspb.Int64Value `protobuf:"bytes,7,opt,name=wrap_int64,json=wrapInt64,proto3" json:"wrap_int64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int64PathRequest) Reset() {
	*x = Int64PathRequest{}
	mi := &file_example_path_path_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64PathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64PathRequest) ProtoMessage() {}

func (x *Int64PathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_path_path_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64PathRequest.ProtoReflect.Descriptor instead.
func (*Int64PathRequest) Descriptor() ([]byte, []int) {
	return file_example_path_path_proto_rawDescGZIP(), []int{2}
}

func (x *Int64PathRequest) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

func (x *Int64PathRequest) GetSint64() int64 {
	if x != nil {
		return x.Sint64
	}
	return 0
}

func (x *Int64PathRequest) GetSfixed64() int64 {
	if x != nil {
		return x.Sfixed64
	}
	return 0
}

func (x *Int64PathRequest) GetOptInt64() int64 {
	if x != nil && x.OptInt64 != nil {
		return *x.OptInt64
	}
	return 0
}

func (x *Int64PathRequest) GetOptSint64() int64 {
	if x != nil && x.OptSint64 != nil {
		return *x.OptSint64
	}
	return 0
}

func (x *Int64PathRequest) GetOptSfixed64() int64 {
	if x != nil && x.OptSfixed64 != nil {
		return *x.OptSfixed64
	}
	return 0
}

func (x *Int64PathRequest) GetWrapInt64() *wrapperspb.Int64Value {
	if x != nil {
		return x.WrapInt64
	}
	return nil
}

type Uint32PathRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Uint32        uint32                  `protobuf:"varint,1,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Fixed32       uint32                  `protobuf:"fixed32,2,opt,name=fixed32,proto3" json:"fixed32,omitempty"`
	OptUint32     *uint32                 `protobuf:"varint,3,opt,name=opt_uint32,json=optUint32,proto3,oneof" json:"opt_uint32,omitempty"`
	OptFixed32    *uint32                 `protobuf:"fixed32,4,opt,name=opt_fixed32,json=optFixed32,proto3,oneof" json:"opt_fixed32,omitempty"`
	WrapUint32    *wrapperspb.UInt32Value `protobuf:"bytes,5,opt,name=wrap_uint32,json=wrapUint32,proto3" json:"wrap_uint32,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Uint32PathRequest) Reset() {
	*x = Uint32PathRequest{}
	mi := &file_example_path_path_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uint32PathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint32PathRequest) ProtoMessage() {}

func (x *Uint32PathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_path_path_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint32PathRequest.ProtoReflect.Descriptor instead.
func (*Uint32PathRequest) Descriptor() ([]byte, []int) {
	return file_example_path_path_proto_rawDescGZIP(), []int{3}
}

func (x *Uint32PathRequest) GetUint32() uint32 {
	if x != nil {
		return x.Uint32
	}
	return 0
}

func (x *Uint32PathRequest) GetFixed32() uint32 {
	if x != nil {
		return x.Fixed32
	}
	return 0
}

func (x *Uint32PathRequest) GetOptUint32() uint32 {
	if x != nil && x.OptUint32 != nil {
		return *x.OptUint32
	}
	return 0
}

func (x *Uint32PathRequest) GetOptFixed32() uint32 {
	if x != nil && x.OptFixed32 != nil {
		return *x.OptFixed32
	}
	return 0
}

func (x *Uint32PathRequest) GetWrapUint32() *wrapperspb.UInt32Value {
	if x != nil {
		return x.WrapUint32
	}
	return nil
}

type Uint64PathRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Uint64        uint64                  `protobuf:"varint,1,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Fixed64       uint64                  `protobuf:"fixed64,2,opt,name=fixed64,proto3" json:"fixed64,omitempty"`
	OptUint64     *uint64                 `protobuf:"varint,3,opt,name=opt_uint64,json=optUint64,proto3,oneof" json:"opt_uint64,omitempty"`
	OptFixed64    *uint64                 `protobuf:"fixed64,4,opt,name=opt_fixed64,json=optFixed64,proto3,oneof" json:"opt_fixed64,omitempty"`
	WrapUint64    *wrapperspb.UInt64Value `protobuf:"bytes,5,opt,name=wrap_uint64,json=wrapUint64,proto3" json:"wrap_uint64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Uint64PathRequest) Reset() {
	*x = Uint64PathRequest{}
	mi := &file_example_path_path_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uint64PathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint64PathRequest) ProtoMessage() {}

func (x *Uint64PathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_path_path_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint64PathRequest.ProtoReflect.Descriptor instead.
func (*Uint64PathRequest) Descriptor() ([]byte, []int) {
	return file_example_path_path_proto_rawDescGZIP(), []int{4}
}

func (x *Uint64PathRequest) GetUint64() uint64 {
	if x != nil {
		return x.Uint64
	}
	return 0
}

func (x *Uint64PathRequest) GetFixed64() uint64 {
	if x != nil {
		return x.Fixed64
	}
	return 0
}

func (x *Uint64PathRequest) GetOptUint64() uint64 {
	if x != nil && x.OptUint64 != nil {
		return *x.OptUint64
	}
	return 0
}

func (x *Uint64PathRequest) GetOptFixed64() uint64 {
	if x != nil && x.OptFixed64 != nil {
		return *x.OptFixed64
	}
	return 0
}

func (x *Uint64PathRequest) GetWrapUint64() *wrapperspb.UInt64Value {
	if x != nil {
		return x.WrapUint64
	}
	return nil
}

type FloatPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Float         float32                `protobuf:"fixed32,1,opt,name=float,proto3" json:"float,omitempty"`
	OptFloat      *float32               `protobuf:"fixed32,2,opt,name=opt_float,json=optFloat,proto3,oneof" json:"opt_float,omitempty"`
	WrapFloat     *wrapperspb.FloatValue `protobuf:"bytes,3,opt,name=wrap_float,json=wrapFloat,proto3" json:"wrap_float,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatPathRequest) Reset() {
	*x = FloatPathRequest{}
	mi := &file_example_path_path_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatPathRequest) ProtoMessage() {}

func (x *FloatPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_path_path_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatPathRequest.ProtoReflect.Descriptor instead.
func (*FloatPathRequest) Descriptor() ([]byte, []int) {
	return file_example_path_path_proto_rawDescGZIP(), []int{5}
}

func (x *FloatPathRequest) GetFloat() float32 {
	if x != nil {
		return x.Float
	}
	return 0
}

func (x *FloatPathRequest) GetOptFloat() float32 {
	if x != nil && x.OptFloat != nil {
		return *x.OptFloat
	}
	return 0
}

func (x *FloatPathRequest) GetWrapFloat() *wrapperspb.FloatValue {
	if x != nil {
		return x.WrapFloat
	}
	return nil
}

type DoublePathRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Double        float64                 `protobuf:"fixed64,1,opt,name=double,proto3" json:"double,omitempty"`
	OptDouble     *float64                `protobuf:"fixed64,2,opt,name=opt_double,json=optDouble,proto3,oneof" json:"opt_double,omitempty"`
	WrapDouble    *wrapperspb.DoubleValue `protobuf:"bytes,3,opt,name=wrap_double,json=wrapDouble,proto3" json:"wrap_double,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoublePathRequest) Reset() {
	*x = DoublePathRequest{}
	mi := &file_example_path_path_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoublePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoublePathRequest) ProtoMessage() {}

func (x *DoublePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_path_path_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoublePathRequest.ProtoReflect.Descriptor instead.
func (*DoublePathRequest) Descriptor() ([]byte, []int) {
	return file_example_path_path_proto_rawDescGZIP(), []int{6}
}

func (x *DoublePathRequest) GetDouble() float64 {
	if x != nil {
		return x.Double
	}
	return 0
}

func (x *DoublePathRequest) GetOptDouble() float64 {
	if x != nil && x.OptDouble != nil {
		return *x.OptDouble
	}
	return 0
}

func (x *DoublePathRequest) GetWrapDouble() *wrapperspb.DoubleValue {
	if x != nil {
		return x.WrapDouble
	}
	return nil
}

type StringPathRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	String_       string                  `protobuf:"bytes,1,opt,name=string,proto3" json:"string,omitempty"`
	OptString     *string                 `protobuf:"bytes,2,opt,name=opt_string,json=optString,proto3,oneof" json:"opt_string,omitempty"`
	WrapString    *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=wrap_string,json=wrapString,proto3" json:"wrap_string,omitempty"`
	MultiString   string                  `protobuf:"bytes,4,opt,name=multi_string,json=multiString,proto3" json:"multi_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringPathRequest) Reset() {
	*x = StringPathRequest{}
	mi := &file_example_path_path_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringPathRequest) ProtoMessage() {}

func (x *StringPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_path_path_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringPathRequest.ProtoReflect.Descriptor instead.
func (*StringPathRequest) Descriptor() ([]byte, []int) {
	return file_example_path_path_proto_rawDescGZIP(), []int{7}
}

func (x *StringPathRequest) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *StringPathRequest) GetOptString() string {
	if x != nil && x.OptString != nil {
		return *x.OptString
	}
	return ""
}

func (x *StringPathRequest) GetWrapString() *wrapperspb.StringValue {
	if x != nil {
		return x.WrapString
	}
	return nil
}

func (x *StringPathRequest) GetMultiString() string {
	if x != nil {
		return x.MultiString
	}
	return ""
}

type EnumPathRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        EnumPathRequest_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=leo.goose.example.path.v1.EnumPathRequest_Status" json:"status,omitempty"`
	OptStatus     *EnumPathRequest_Status `protobuf:"varint,2,opt,name=opt_status,json=optStatus,proto3,enum=leo.goose.example.path.v1.EnumPathRequest_Status,oneof" json:"opt_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumPathRequest) Reset() {
	*x = EnumPathRequest{}
	mi := &file_example_path_path_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumPathRequest) ProtoMessage() {}

func (x *EnumPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_path_path_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumPathRequest.ProtoReflect.Descriptor instead.
func (*EnumPathRequest) Descriptor() ([]byte, []int) {
	return file_example_path_path_proto_rawDescGZIP(), []int{8}
}

func (x *EnumPathRequest) GetStatus() EnumPathRequest_Status {
	if x != nil {
		return x.Status
	}
	return EnumPathRequest_UNKNOWN
}

func (x *EnumPathRequest) GetOptStatus() EnumPathRequest_Status {
	if x != nil && x.OptStatus != nil {
		return *x.OptStatus
	}
	return EnumPathRequest_UNKNOWN
}

var File_example_path_path_proto protoreflect.FileDescriptor

const file_example_path_path_proto_rawDesc = "" +
	"\n" +
	"\x17example/path/path.proto\x12\x19leo.goose.example.path.v1\x1a\x19google/api/httpbody.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x8b\x01\n" +
	"\x0fBoolPathRequest\x12\x12\n" +
	"\x04bool\x18\x01 \x01(\bR\x04bool\x12\x1e\n" +
	"\bopt_bool\x18\x02 \x01(\bH\x00R\aoptBool\x88\x01\x01\x127\n" +
	"\twrap_bool\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\bwrapBoolB\v\n" +
	"\t_opt_bool\"\xb4\x02\n" +
	"\x10Int32PathRequest\x12\x14\n" +
	"\x05int32\x18\x01 \x01(\x05R\x05int32\x12\x16\n" +
	"\x06sint32\x18\x02 \x01(\x11R\x06sint32\x12\x1a\n" +
	"\bsfixed32\x18\x03 \x01(\x0fR\bsfixed32\x12 \n" +
	"\topt_int32\x18\x04 \x01(\x05H\x00R\boptInt32\x88\x01\x01\x12\"\n" +
	"\n" +
	"opt_sint32\x18\x05 \x01(\x11H\x01R\toptSint32\x88\x01\x01\x12&\n" +
	"\fopt_sfixed32\x18\x06 \x01(\x0fH\x02R\voptSfixed32\x88\x01\x01\x12:\n" +
	"\n" +
	"wrap_int32\x18\a \x01(\v2\x1b.google.protobuf.Int32ValueR\twrapInt32B\f\n" +
	"\n" +
	"_opt_int32B\r\n" +
	"\v_opt_sint32B\x0f\n" +
	"\r_opt_sfixed32\"\xb4\x02\n" +
	"\x10Int64PathRequest\x12\x14\n" +
	"\x05int64\x18\x01 \x01(\x03R\x05int64\x12\x16\n" +
	"\x06sint64\x18\x02 \x01(\x12R\x06sint64\x12\x1a\n" +
	"\bsfixed64\x18\x03 \x01(\x10R\bsfixed64\x12 \n" +
	"\topt_int64\x18\x04 \x01(\x03H\x00R\boptInt64\x88\x01\x01\x12\"\n" +
	"\n" +
	"opt_sint64\x18\x05 \x01(\x12H\x01R\toptSint64\x88\x01\x01\x12&\n" +
	"\fopt_sfixed64\x18\x06 \x01(\x10H\x02R\voptSfixed64\x88\x01\x01\x12:\n" +
	"\n" +
	"wrap_int64\x18\a \x01(\v2\x1b.google.protobuf.Int64ValueR\twrapInt64B\f\n" +
	"\n" +
	"_opt_int64B\r\n" +
	"\v_opt_sint64B\x0f\n" +
	"\r_opt_sfixed64\"\xed\x01\n" +
	"\x11Uint32PathRequest\x12\x16\n" +
	"\x06uint32\x18\x01 \x01(\rR\x06uint32\x12\x18\n" +
	"\afixed32\x18\x02 \x01(\aR\afixed32\x12\"\n" +
	"\n" +
	"opt_uint32\x18\x03 \x01(\rH\x00R\toptUint32\x88\x01\x01\x12$\n" +
	"\vopt_fixed32\x18\x04 \x01(\aH\x01R\n" +
	"optFixed32\x88\x01\x01\x12=\n" +
	"\vwrap_uint32\x18\x05 \x01(\v2\x1c.google.protobuf.UInt32ValueR\n" +
	"wrapUint32B\r\n" +
	"\v_opt_uint32B\x0e\n" +
	"\f_opt_fixed32\"\xed\x01\n" +
	"\x11Uint64PathRequest\x12\x16\n" +
	"\x06uint64\x18\x01 \x01(\x04R\x06uint64\x12\x18\n" +
	"\afixed64\x18\x02 \x01(\x06R\afixed64\x12\"\n" +
	"\n" +
	"opt_uint64\x18\x03 \x01(\x04H\x00R\toptUint64\x88\x01\x01\x12$\n" +
	"\vopt_fixed64\x18\x04 \x01(\x06H\x01R\n" +
	"optFixed64\x88\x01\x01\x12=\n" +
	"\vwrap_uint64\x18\x05 \x01(\v2\x1c.google.protobuf.UInt64ValueR\n" +
	"wrapUint64B\r\n" +
	"\v_opt_uint64B\x0e\n" +
	"\f_opt_fixed64\"\x94\x01\n" +
	"\x10FloatPathRequest\x12\x14\n" +
	"\x05float\x18\x01 \x01(\x02R\x05float\x12 \n" +
	"\topt_float\x18\x02 \x01(\x02H\x00R\boptFloat\x88\x01\x01\x12:\n" +
	"\n" +
	"wrap_float\x18\x03 \x01(\v2\x1b.google.protobuf.FloatValueR\twrapFloatB\f\n" +
	"\n" +
	"_opt_float\"\x9d\x01\n" +
	"\x11DoublePathRequest\x12\x16\n" +
	"\x06double\x18\x01 \x01(\x01R\x06double\x12\"\n" +
	"\n" +
	"opt_double\x18\x02 \x01(\x01H\x00R\toptDouble\x88\x01\x01\x12=\n" +
	"\vwrap_double\x18\x03 \x01(\v2\x1c.google.protobuf.DoubleValueR\n" +
	"wrapDoubleB\r\n" +
	"\v_opt_double\"\xc0\x01\n" +
	"\x11StringPathRequest\x12\x16\n" +
	"\x06string\x18\x01 \x01(\tR\x06string\x12\"\n" +
	"\n" +
	"opt_string\x18\x02 \x01(\tH\x00R\toptString\x88\x01\x01\x12=\n" +
	"\vwrap_string\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"wrapString\x12!\n" +
	"\fmulti_string\x18\x04 \x01(\tR\vmultiStringB\r\n" +
	"\v_opt_string\"\x83\x02\n" +
	"\x0fEnumPathRequest\x12I\n" +
	"\x06status\x18\x01 \x01(\x0e21.leo.goose.example.path.v1.EnumPathRequest.StatusR\x06status\x12U\n" +
	"\n" +
	"opt_status\x18\x02 \x01(\x0e21.leo.goose.example.path.v1.EnumPathRequest.StatusH\x00R\toptStatus\x88\x01\x01\"?\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\r\n" +
	"\tCANCELLED\x10\x02\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x03B\r\n" +
	"\v_opt_status2\x83\x01\n" +
	"\bBoolPath\x12w\n" +
	"\bBoolPath\x12*.leo.goose.example.path.v1.BoolPathRequest\x1a\x14.google.api.HttpBody\")\x82\xd3\xe4\x93\x02#\x12!/v1/{bool}/{opt_bool}/{wrap_bool}2\xba\x01\n" +
	"\tInt32Path\x12\xac\x01\n" +
	"\tInt32Path\x12+.leo.goose.example.path.v1.Int32PathRequest\x1a\x14.google.api.HttpBody\"\\\x82\xd3\xe4\x93\x02V\x12T/v1/{int32}/{sint32}/{sfixed32}/{opt_int32}/{opt_sint32}/{opt_sfixed32}/{wrap_int32}2\xba\x01\n" +
	"\tInt64Path\x12\xac\x01\n" +
	"\tInt64Path\x12+.leo.goose.example.path.v1.Int64PathRequest\x1a\x14.google.api.HttpBody\"\\\x82\xd3\xe4\x93\x02V\x12T/v1/{int64}/{sint64}/{sfixed64}/{opt_int64}/{opt_sint64}/{opt_sfixed64}/{wrap_int64}2\xa8\x01\n" +
	"\n" +
	"Uint32Path\x12\x99\x01\n" +
	"\n" +
	"Uint32Path\x12,.leo.goose.example.path.v1.Uint32PathRequest\x1a\x14.google.api.HttpBody\"G\x82\xd3\xe4\x93\x02A\x12?/v1/{uint32}/{fixed32}/{opt_uint32}/{opt_fixed32}/{wrap_uint32}2\xa8\x01\n" +
	"\n" +
	"Uint64Path\x12\x99\x01\n" +
	"\n" +
	"Uint64Path\x12,.leo.goose.example.path.v1.Uint64PathRequest\x1a\x14.google.api.HttpBody\"G\x82\xd3\xe4\x93\x02A\x12?/v1/{uint64}/{fixed64}/{opt_uint64}/{opt_fixed64}/{wrap_uint64}2\x89\x01\n" +
	"\tFloatPath\x12|\n" +
	"\tFloatPath\x12+.leo.goose.example.path.v1.FloatPathRequest\x1a\x14.google.api.HttpBody\",\x82\xd3\xe4\x93\x02&\x12$/v1/{float}/{opt_float}/{wrap_float}2\x90\x01\n" +
	"\n" +
	"DoublePath\x12\x81\x01\n" +
	"\n" +
	"DoublePath\x12,.leo.goose.example.path.v1.DoublePathRequest\x1a\x14.google.api.HttpBody\"/\x82\xd3\xe4\x93\x02)\x12'/v1/{double}/{opt_double}/{wrap_double}2\xa2\x01\n" +
	"\n" +
	"StringPath\x12\x93\x01\n" +
	"\n" +
	"StringPath\x12,.leo.goose.example.path.v1.StringPathRequest\x1a\x14.google.api.HttpBody\"A\x82\xd3\xe4\x93\x02;\x129/v1/{string}/{opt_string}/{wrap_string}/{multi_string...}2{\n" +
	"\bEnumPath\x12o\n" +
	"\bEnumPath\x12*.leo.goose.example.path.v1.EnumPathRequest\x1a\x14.google.api.HttpBody\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/{status}/{opt_status}B/Z-github.com/soyacen/goose/example/path/v1;pathb\x06proto3"

var (
	file_example_path_path_proto_rawDescOnce sync.Once
	file_example_path_path_proto_rawDescData []byte
)

func file_example_path_path_proto_rawDescGZIP() []byte {
	file_example_path_path_proto_rawDescOnce.Do(func() {
		file_example_path_path_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_path_path_proto_rawDesc), len(file_example_path_path_proto_rawDesc)))
	})
	return file_example_path_path_proto_rawDescData
}

var file_example_path_path_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_example_path_path_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_example_path_path_proto_goTypes = []any{
	(EnumPathRequest_Status)(0),    // 0: leo.goose.example.path.v1.EnumPathRequest.Status
	(*BoolPathRequest)(nil),        // 1: leo.goose.example.path.v1.BoolPathRequest
	(*Int32PathRequest)(nil),       // 2: leo.goose.example.path.v1.Int32PathRequest
	(*Int64PathRequest)(nil),       // 3: leo.goose.example.path.v1.Int64PathRequest
	(*Uint32PathRequest)(nil),      // 4: leo.goose.example.path.v1.Uint32PathRequest
	(*Uint64PathRequest)(nil),      // 5: leo.goose.example.path.v1.Uint64PathRequest
	(*FloatPathRequest)(nil),       // 6: leo.goose.example.path.v1.FloatPathRequest
	(*DoublePathRequest)(nil),      // 7: leo.goose.example.path.v1.DoublePathRequest
	(*StringPathRequest)(nil),      // 8: leo.goose.example.path.v1.StringPathRequest
	(*EnumPathRequest)(nil),        // 9: leo.goose.example.path.v1.EnumPathRequest
	(*wrapperspb.BoolValue)(nil),   // 10: google.protobuf.BoolValue
	(*wrapperspb.Int32Value)(nil),  // 11: google.protobuf.Int32Value
	(*wrapperspb.Int64Value)(nil),  // 12: google.protobuf.Int64Value
	(*wrapperspb.UInt32Value)(nil), // 13: google.protobuf.UInt32Value
	(*wrapperspb.UInt64Value)(nil), // 14: google.protobuf.UInt64Value
	(*wrapperspb.FloatValue)(nil),  // 15: google.protobuf.FloatValue
	(*wrapperspb.DoubleValue)(nil), // 16: google.protobuf.DoubleValue
	(*wrapperspb.StringValue)(nil), // 17: google.protobuf.StringValue
	(*httpbody.HttpBody)(nil),      // 18: google.api.HttpBody
}
var file_example_path_path_proto_depIdxs = []int32{
	10, // 0: leo.goose.example.path.v1.BoolPathRequest.wrap_bool:type_name -> google.protobuf.BoolValue
	11, // 1: leo.goose.example.path.v1.Int32PathRequest.wrap_int32:type_name -> google.protobuf.Int32Value
	12, // 2: leo.goose.example.path.v1.Int64PathRequest.wrap_int64:type_name -> google.protobuf.Int64Value
	13, // 3: leo.goose.example.path.v1.Uint32PathRequest.wrap_uint32:type_name -> google.protobuf.UInt32Value
	14, // 4: leo.goose.example.path.v1.Uint64PathRequest.wrap_uint64:type_name -> google.protobuf.UInt64Value
	15, // 5: leo.goose.example.path.v1.FloatPathRequest.wrap_float:type_name -> google.protobuf.FloatValue
	16, // 6: leo.goose.example.path.v1.DoublePathRequest.wrap_double:type_name -> google.protobuf.DoubleValue
	17, // 7: leo.goose.example.path.v1.StringPathRequest.wrap_string:type_name -> google.protobuf.StringValue
	0,  // 8: leo.goose.example.path.v1.EnumPathRequest.status:type_name -> leo.goose.example.path.v1.EnumPathRequest.Status
	0,  // 9: leo.goose.example.path.v1.EnumPathRequest.opt_status:type_name -> leo.goose.example.path.v1.EnumPathRequest.Status
	1,  // 10: leo.goose.example.path.v1.BoolPath.BoolPath:input_type -> leo.goose.example.path.v1.BoolPathRequest
	2,  // 11: leo.goose.example.path.v1.Int32Path.Int32Path:input_type -> leo.goose.example.path.v1.Int32PathRequest
	3,  // 12: leo.goose.example.path.v1.Int64Path.Int64Path:input_type -> leo.goose.example.path.v1.Int64PathRequest
	4,  // 13: leo.goose.example.path.v1.Uint32Path.Uint32Path:input_type -> leo.goose.example.path.v1.Uint32PathRequest
	5,  // 14: leo.goose.example.path.v1.Uint64Path.Uint64Path:input_type -> leo.goose.example.path.v1.Uint64PathRequest
	6,  // 15: leo.goose.example.path.v1.FloatPath.FloatPath:input_type -> leo.goose.example.path.v1.FloatPathRequest
	7,  // 16: leo.goose.example.path.v1.DoublePath.DoublePath:input_type -> leo.goose.example.path.v1.DoublePathRequest
	8,  // 17: leo.goose.example.path.v1.StringPath.StringPath:input_type -> leo.goose.example.path.v1.StringPathRequest
	9,  // 18: leo.goose.example.path.v1.EnumPath.EnumPath:input_type -> leo.goose.example.path.v1.EnumPathRequest
	18, // 19: leo.goose.example.path.v1.BoolPath.BoolPath:output_type -> google.api.HttpBody
	18, // 20: leo.goose.example.path.v1.Int32Path.Int32Path:output_type -> google.api.HttpBody
	18, // 21: leo.goose.example.path.v1.Int64Path.Int64Path:output_type -> google.api.HttpBody
	18, // 22: leo.goose.example.path.v1.Uint32Path.Uint32Path:output_type -> google.api.HttpBody
	18, // 23: leo.goose.example.path.v1.Uint64Path.Uint64Path:output_type -> google.api.HttpBody
	18, // 24: leo.goose.example.path.v1.FloatPath.FloatPath:output_type -> google.api.HttpBody
	18, // 25: leo.goose.example.path.v1.DoublePath.DoublePath:output_type -> google.api.HttpBody
	18, // 26: leo.goose.example.path.v1.StringPath.StringPath:output_type -> google.api.HttpBody
	18, // 27: leo.goose.example.path.v1.EnumPath.EnumPath:output_type -> google.api.HttpBody
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_example_path_path_proto_init() }
func file_example_path_path_proto_init() {
	if File_example_path_path_proto != nil {
		return
	}
	file_example_path_path_proto_msgTypes[0].OneofWrappers = []any{}
	file_example_path_path_proto_msgTypes[1].OneofWrappers = []any{}
	file_example_path_path_proto_msgTypes[2].OneofWrappers = []any{}
	file_example_path_path_proto_msgTypes[3].OneofWrappers = []any{}
	file_example_path_path_proto_msgTypes[4].OneofWrappers = []any{}
	file_example_path_path_proto_msgTypes[5].OneofWrappers = []any{}
	file_example_path_path_proto_msgTypes[6].OneofWrappers = []any{}
	file_example_path_path_proto_msgTypes[7].OneofWrappers = []any{}
	file_example_path_path_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_path_path_proto_rawDesc), len(file_example_path_path_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   9,
		},
		GoTypes:           file_example_path_path_proto_goTypes,
		DependencyIndexes: file_example_path_path_proto_depIdxs,
		EnumInfos:         file_example_path_path_proto_enumTypes,
		MessageInfos:      file_example_path_path_proto_msgTypes,
	}.Build()
	File_example_path_path_proto = out.File
	file_example_path_path_proto_goTypes = nil
	file_example_path_path_proto_depIdxs = nil
}
