package main

import (
	"context"
	"io"
	"net/http"
)

// ---------------------------------------------------------------------------
// Domain types (would be generated from .proto)
// ---------------------------------------------------------------------------

// ListExpiredCreditBucketsRequest is the request message for the stream service.
type ListExpiredCreditBucketsRequest struct {
	// Filter is an optional filter expression applied server-side.
	Filter string `json:"filter,omitempty"`
}

// CreditBucket represents a single expired credit bucket entry.
type CreditBucket struct {
	BucketID string `json:"bucket_id"`
	Amount   int64  `json:"amount"`
	Expired  bool   `json:"expired"`
}

// ListExpiredCreditBucketsResponse is the response message for the stream service.
type ListExpiredCreditBucketsResponse struct {
	Buckets []*CreditBucket `json:"buckets,omitempty"`
	Total   int64           `json:"total"`
}

// ---------------------------------------------------------------------------
// Client-side streaming interfaces (generated by protoc-gen-goose)
// ---------------------------------------------------------------------------

// StreamService is the client-side interface for the stream service.
// Each method creates a new streaming RPC and returns a typed stream client.
//
// Generated by protoc-gen-goose from the service definition.
type StreamService interface {
	// ClientStrean opens a client-streaming RPC. The client sends multiple
	// requests and the server responds with a single aggregated response.
	ClientStrean(ctx context.Context) (ClientStreamingClient[ListExpiredCreditBucketsRequest, ListExpiredCreditBucketsResponse], error)

	// ServerStrean opens a server-streaming RPC. The client sends one request
	// and the server streams back multiple responses.
	ServerStrean(ctx context.Context, in *ListExpiredCreditBucketsRequest) (ServerStreamingClient[ListExpiredCreditBucketsResponse], error)

	// Bid opens a bidirectional-streaming RPC. Both sides can send messages
	// concurrently.
	Bid(ctx context.Context) (BidiStreamingClient[ListExpiredCreditBucketsRequest, ListExpiredCreditBucketsResponse], error)
}

// ClientStreamingClient represents the client side of a client-streaming
// (many requests, one response) RPC. It is generic over both the request
// and response message types. It is used in generated code.
type ClientStreamingClient[Req any, Res any] interface {
	// Send sends a request message to the server. The client may call Send
	// multiple times to send multiple messages to the server. On error, Send
	// aborts the stream. If the error was generated by the client, the status
	// is returned directly. Otherwise, io.EOF is returned, and the status of
	// the stream may be discovered using CloseAndRecv().
	Send(*Req) error

	// CloseAndRecv closes the request stream and waits for the server's
	// response. This method must be called once and only once after sending
	// all request messages. Any error returned is implemented by the status
	// package.
	CloseAndRecv() (*Res, error)

	// ClientStream is embedded to provide Context, Header, and Trailer
	// functionality. No other methods in the ClientStream should be called
	// directly.
	ClientStream
}

// ServerStreamingClient represents the client side of a server-streaming (one
// request, many responses) RPC. It is generic over the type of the response
// message. It is used in generated code.
type ServerStreamingClient[Res any] interface {
	// Recv receives the next response message from the server. The client may
	// repeatedly call Recv to read messages from the response stream. If
	// io.EOF is returned, the stream has terminated with an OK status. Any
	// other error is compatible with the status package and indicates the
	// RPC's status code and message.
	Recv() (*Res, error)

	// ClientStream is embedded to provide Context, Header, and Trailer
	// functionality. No other methods in the ClientStream should be called
	// directly.
	ClientStream
}

// BidiStreamingClient represents the client side of a bidirectional-streaming
// (many requests, many responses) RPC. It is generic over both the type of the
// request message stream and the type of the response message stream. It is
// used in generated code.
type BidiStreamingClient[Req any, Res any] interface {
	// Send sends a request message to the server. The client may call Send
	// multiple times to send multiple messages to the server. On error, Send
	// aborts the stream. If the error was generated by the client, the status
	// is returned directly. Otherwise, io.EOF is returned, and the status of
	// the stream may be discovered using Recv().
	Send(*Req) error

	// Recv receives the next response message from the server. The client may
	// repeatedly call Recv to read messages from the response stream. If
	// io.EOF is returned, the stream has terminated with an OK status. Any
	// other error is compatible with the status package and indicates the
	// RPC's status code and message.
	Recv() (*Res, error)

	// ClientStream is embedded to provide Context, Header, Trailer, and
	// CloseSend functionality. No other methods in the ClientStream should be
	// called directly.
	ClientStream
}

// ClientStream defines the client-side behavior of a streaming RPC.
//
// All errors returned from ClientStream methods are compatible with the
// status package.
type ClientStream interface {
	// Header returns the header metadata received from the server if there
	// is any. It blocks if the metadata is not ready to read. If the metadata
	// is nil and the error is also nil, then the stream was terminated without
	// headers, and the status can be discovered by calling RecvMsg.
	Header() (http.Header, error)
	// Trailer returns the trailer metadata from the server, if there is any.
	// It must only be called after stream.CloseAndRecv has returned, or
	// stream.Recv has returned a non-nil error (including io.EOF).
	Trailer() http.Header
	// CloseSend closes the send direction of the stream. This method always
	// returns a nil error. The status of the stream may be discovered using
	// RecvMsg. It is also not safe to call CloseSend concurrently with SendMsg.
	CloseSend() error
	// Context returns the context for this stream.
	//
	// It should not be called until after Header or RecvMsg has returned. Once
	// called, subsequent client-side retries are disabled.
	Context() context.Context
	// SendMsg is generally called by generated code. On error, SendMsg aborts
	// the stream. If the error was generated by the client, the status is
	// returned directly; otherwise, io.EOF is returned and the status of
	// the stream may be discovered using RecvMsg. For unary or server-streaming
	// RPCs (StreamDesc.ClientStreams is false), a nil error is returned
	// unconditionally.
	//
	// SendMsg blocks until:
	//   - There is sufficient flow control to schedule m with the transport, or
	//   - The stream is done, or
	//   - The stream breaks.
	//
	// SendMsg does not wait until the message is received by the server. An
	// untimely stream closure may result in lost messages. To ensure delivery,
	// users should ensure the RPC completed successfully using RecvMsg.
	//
	// It is safe to have a goroutine calling SendMsg and another goroutine
	// calling RecvMsg on the same stream at the same time, but it is not safe
	// to call SendMsg on the same stream in different goroutines. It is also
	// not safe to call CloseSend concurrently with SendMsg.
	//
	// It is not safe to modify the message after calling SendMsg. Tracing
	// libraries and stats handlers may use the message lazily.
	SendMsg(m any) error
	// RecvMsg blocks until it receives a message into m or the stream is
	// done. It returns io.EOF when the stream completes successfully. On
	// any other error, the stream is aborted and the error contains the RPC
	// status.
	//
	// It is safe to have a goroutine calling SendMsg and another goroutine
	// calling RecvMsg on the same stream at the same time, but it is not
	// safe to call RecvMsg on the same stream in different goroutines.
	RecvMsg(m any) error
}

// ---------------------------------------------------------------------------
// Server-side streaming interfaces (generated by protoc-gen-goose)
// ---------------------------------------------------------------------------

// StreamServiceServer is the server-side interface for the stream service.
// User code implements this interface; the generated handler layer routes
// incoming WebSocket connections to the appropriate method.
type StreamServiceServer interface {
	// ClientStream handles a client-streaming RPC. The server reads multiple
	// request messages from the stream and sends a single response via
	// SendAndClose.
	ClientStream(ServerClientStream[ListExpiredCreditBucketsRequest, ListExpiredCreditBucketsResponse]) error

	// ServerStream handles a server-streaming RPC. The server receives one
	// request and sends multiple response messages via Send.
	ServerStream(*ListExpiredCreditBucketsRequest, ServerServerStream[ListExpiredCreditBucketsResponse]) error

	// BidStream handles a bidirectional-streaming RPC. Both sides can send
	// messages concurrently.
	BidStream(ServerBidiStream[ListExpiredCreditBucketsRequest, ListExpiredCreditBucketsResponse]) error
}

// ServerStream is the base interface for all server-side streams.
// It mirrors ClientStream on the server side.
type ServerStream interface {
	// Header returns the response header metadata.
	Header() http.Header
	// SetHeader sets the response header metadata.
	SetHeader(http.Header)
	// Trailer returns the trailer metadata that will be sent after the RPC
	// completes.
	Trailer() http.Header
	// SetTrailer sets the trailer metadata.
	SetTrailer(http.Header)
	// Context returns the context for this stream.
	Context() context.Context
	// SendMsg serializes m using the stream's Codec and sends it to the client.
	SendMsg(m any) error
	// RecvMsg reads a message from the client and deserializes it into m
	// using the stream's Codec. Returns io.EOF when the client closes the
	// stream.
	RecvMsg(m any) error
}

// ServerClientStream is the server-side interface for a client-streaming RPC
// (many requests, one response).
type ServerClientStream[Req any, Res any] interface {
	ServerStream
	// Recv reads the next request message from the client stream.
	// Returns io.EOF when the client has closed the stream.
	Recv() (*Req, error)
	// SendAndClose sends the final response and closes the stream.
	// It must be called exactly once.
	SendAndClose(*Res) error
}

// ServerServerStream is the server-side interface for a server-streaming RPC
// (one request, many responses).
type ServerServerStream[Res any] interface {
	ServerStream
	// Send writes a response message to the client stream.
	Send(*Res) error
}

// ServerBidiStream is the server-side interface for a bidirectional-streaming
// RPC (many requests, many responses).
type ServerBidiStream[Req any, Res any] interface {
	ServerStream
	// Recv reads the next request message from the client stream.
	// Returns io.EOF when the client has closed the stream.
	Recv() (*Req, error)
	// Send writes a response message to the client stream.
	Send(*Res) error
}

// Ensure io.EOF is referenced so the import is not flagged as unused.
var _ = io.EOF
