package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"

	"github.com/soyacen/goose/cmd/protoc-gen-goose/client"
	"github.com/soyacen/goose/cmd/protoc-gen-goose/constant"
	"github.com/soyacen/goose/cmd/protoc-gen-goose/parser"
	"github.com/soyacen/goose/cmd/protoc-gen-goose/server"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

var flags flag.FlagSet

var Version = "v1.7.8"

func main() {
	if len(os.Args) == 2 && os.Args[1] == "--version" {
		fmt.Fprintf(os.Stdout, "%v %v\n", filepath.Base(os.Args[0]), Version)
		os.Exit(0)
	}
	options := &protogen.Options{ParamFunc: flags.Set}
	options.Run(func(plugin *protogen.Plugin) error {
		plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		return generate(plugin)
	})
}

func generate(plugin *protogen.Plugin) error {
	for _, file := range plugin.Files {
		if !file.Generate {
			continue
		}
		if len(file.Services) <= 0 {
			continue
		}
		services, err := parser.NewServices(file)
		if err != nil {
			return err
		}
		filename := file.GeneratedFilenamePrefix + "_goose.pb.go"
		g := plugin.NewGeneratedFile(filename, file.GoImportPath)
		g.P("// Code generated by protoc-gen-goose. DO NOT EDIT.")
		g.P()
		g.P("package ", file.GoPackageName)
		g.P()

		for _, service := range services {
			if err := GenerateServices(service, g); err != nil {
				return err
			}

			srvGen := new(server.Generator)
			if err := srvGen.GenerateAppendServerFunc(service, g); err != nil {
				return err
			}
			if err := srvGen.GenerateHandlers(service, g); err != nil {
				return err
			}
			if err := srvGen.GenerateDecodeRequest(service, g); err != nil {
				return err
			}
			if err := srvGen.GenerateEncodeResponse(service, g); err != nil {
				return err
			}

			cliGen := new(client.Generator)
			if err := cliGen.GenerateNewClient(service, g); err != nil {
				return err
			}
			if err := cliGen.GenerateClient(service, g); err != nil {
				return err
			}
			if err := cliGen.GenerateRequestEncoder(service, g); err != nil {
				return err
			}
			if err := cliGen.GenerateResponseDecoder(service, g); err != nil {
				return err
			}

			if err := GenerateDescs(service, g); err != nil {
				return err
			}
		}

	}
	return nil
}

func GenerateServices(service *parser.Service, g *protogen.GeneratedFile) error {
	g.P("type ", service.ServiceName(), " interface {")
	for _, endpoint := range service.Endpoints {
		g.P(endpoint.Name(), "(ctx ", constant.ContextIdent, ", req *", endpoint.InputGoIdent(), ") (*", endpoint.OutputGoIdent(), ", error)")
	}
	g.P("}")
	g.P()
	return nil
}

func GenerateDescs(service *parser.Service, g *protogen.GeneratedFile) error {
	for _, endpoint := range service.Endpoints {
		g.P("var ", endpoint.DescName(), " = &", constant.DescIdent, "{")
		g.P("RouteInfo: &", constant.RouteInfoIdent, "{")
		g.P("HttpMethod: ", strconv.Quote(endpoint.Method()), ",")
		g.P("Pattern: ", strconv.Quote(endpoint.Path()), ",")
		g.P("FullMethod: ", strconv.Quote(endpoint.FullName()), ",")
		g.P("},")
		g.P("}")
		g.P()
	}
	return nil
}
