// Code generated by protoc-gen-goose. DO NOT EDIT.

package body

import (
	bytes "bytes"
	context "context"
	errors "errors"
	goose "github.com/soyacen/goose"
	client "github.com/soyacen/goose/client"
	resolver "github.com/soyacen/goose/client/resolver"
	server "github.com/soyacen/goose/server"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	http "google.golang.org/genproto/googleapis/rpc/http"
	protojson "google.golang.org/protobuf/encoding/protojson"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http1 "net/http"
)

type BodyService interface {
	StarBody(ctx context.Context, req *BodyRequest) (*Response, error)
	NamedBody(ctx context.Context, req *NamedBodyRequest) (*Response, error)
	NonBody(ctx context.Context, req *emptypb.Empty) (*Response, error)
	HttpBodyStarBody(ctx context.Context, req *httpbody.HttpBody) (*Response, error)
	HttpBodyNamedBody(ctx context.Context, req *HttpBodyRequest) (*Response, error)
	HttpRequest(ctx context.Context, req *http.HttpRequest) (*Response, error)
}

func AppendBodyHttpRoute(router *http1.ServeMux, service BodyService, opts ...server.Option) *http1.ServeMux {
	if router == nil {
		router = http1.NewServeMux()
	}
	options := server.NewOptions(opts...)
	handler := bodyHandler{
		service: service,
		decoder: bodyRequestDecoder{
			unmarshalOptions: options.UnmarshalOptions(),
		},
		encoder: bodyResponseEncoder{
			marshalOptions:   options.MarshalOptions(),
			unmarshalOptions: options.UnmarshalOptions(),
		},
		errorEncoder:            options.ErrorEncoder(),
		shouldFailFast:          options.ShouldFailFast(),
		onValidationErrCallback: options.OnValidationErrCallback(),
		middleware:              server.Chain(options.Middlewares()...),
	}
	router.Handle("POST /v1/star/body", http1.HandlerFunc(handler.StarBody))
	router.Handle("POST /v1/named/body", http1.HandlerFunc(handler.NamedBody))
	router.Handle("GET /v1/user_body", http1.HandlerFunc(handler.NonBody))
	router.Handle("PUT /v1/http/body/star/body", http1.HandlerFunc(handler.HttpBodyStarBody))
	router.Handle("PUT /v1/http/body/named/body", http1.HandlerFunc(handler.HttpBodyNamedBody))
	router.Handle("PUT /v1/http/request", http1.HandlerFunc(handler.HttpRequest))
	return router
}

type bodyHandler struct {
	service                 BodyService
	decoder                 bodyRequestDecoder
	encoder                 bodyResponseEncoder
	errorEncoder            goose.ErrorEncoder
	shouldFailFast          bool
	onValidationErrCallback goose.OnValidationErrCallback
	middleware              server.Middleware
}

func (h bodyHandler) StarBody(response http1.ResponseWriter, request *http1.Request) {
	invoke := func(response http1.ResponseWriter, request *http1.Request) {
		ctx := request.Context()
		req, err := h.decoder.StarBody(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := goose.ValidateRequest(ctx, req, h.shouldFailFast, h.onValidationErrCallback); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		resp, err := h.service.StarBody(ctx, req)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := h.encoder.StarBody(ctx, response, resp); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_body_v1_Body_StarBody_Desc.RouteInfo)
}

func (h bodyHandler) NamedBody(response http1.ResponseWriter, request *http1.Request) {
	invoke := func(response http1.ResponseWriter, request *http1.Request) {
		ctx := request.Context()
		req, err := h.decoder.NamedBody(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := goose.ValidateRequest(ctx, req, h.shouldFailFast, h.onValidationErrCallback); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		resp, err := h.service.NamedBody(ctx, req)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := h.encoder.NamedBody(ctx, response, resp); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_body_v1_Body_NamedBody_Desc.RouteInfo)
}

func (h bodyHandler) NonBody(response http1.ResponseWriter, request *http1.Request) {
	invoke := func(response http1.ResponseWriter, request *http1.Request) {
		ctx := request.Context()
		req, err := h.decoder.NonBody(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := goose.ValidateRequest(ctx, req, h.shouldFailFast, h.onValidationErrCallback); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		resp, err := h.service.NonBody(ctx, req)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := h.encoder.NonBody(ctx, response, resp); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_body_v1_Body_NonBody_Desc.RouteInfo)
}

func (h bodyHandler) HttpBodyStarBody(response http1.ResponseWriter, request *http1.Request) {
	invoke := func(response http1.ResponseWriter, request *http1.Request) {
		ctx := request.Context()
		req, err := h.decoder.HttpBodyStarBody(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := goose.ValidateRequest(ctx, req, h.shouldFailFast, h.onValidationErrCallback); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		resp, err := h.service.HttpBodyStarBody(ctx, req)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := h.encoder.HttpBodyStarBody(ctx, response, resp); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_body_v1_Body_HttpBodyStarBody_Desc.RouteInfo)
}

func (h bodyHandler) HttpBodyNamedBody(response http1.ResponseWriter, request *http1.Request) {
	invoke := func(response http1.ResponseWriter, request *http1.Request) {
		ctx := request.Context()
		req, err := h.decoder.HttpBodyNamedBody(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := goose.ValidateRequest(ctx, req, h.shouldFailFast, h.onValidationErrCallback); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		resp, err := h.service.HttpBodyNamedBody(ctx, req)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := h.encoder.HttpBodyNamedBody(ctx, response, resp); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_body_v1_Body_HttpBodyNamedBody_Desc.RouteInfo)
}

func (h bodyHandler) HttpRequest(response http1.ResponseWriter, request *http1.Request) {
	invoke := func(response http1.ResponseWriter, request *http1.Request) {
		ctx := request.Context()
		req, err := h.decoder.HttpRequest(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := goose.ValidateRequest(ctx, req, h.shouldFailFast, h.onValidationErrCallback); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		resp, err := h.service.HttpRequest(ctx, req)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := h.encoder.HttpRequest(ctx, response, resp); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
	}
	server.Invoke(h.middleware, response, request, invoke, _leo_goose_example_body_v1_Body_HttpRequest_Desc.RouteInfo)
}

type bodyRequestDecoder struct {
	unmarshalOptions protojson.UnmarshalOptions
}

func (decoder bodyRequestDecoder) StarBody(ctx context.Context, request *http1.Request) (*BodyRequest, error) {
	req := &BodyRequest{}
	ok, err := server.CustomDecodeRequest(ctx, request, req)
	if err != nil {
		return nil, err
	}
	if ok {
		return req, nil
	}
	if err := server.DecodeRequest(ctx, request, req, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	return req, nil
}
func (decoder bodyRequestDecoder) NamedBody(ctx context.Context, request *http1.Request) (*NamedBodyRequest, error) {
	req := &NamedBodyRequest{}
	ok, err := server.CustomDecodeRequest(ctx, request, req)
	if err != nil {
		return nil, err
	}
	if ok {
		return req, nil
	}
	if req.Body == nil {
		req.Body = &NamedBodyRequest_Body{}
	}
	if err := server.DecodeRequest(ctx, request, req.Body, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	return req, nil
}
func (decoder bodyRequestDecoder) NonBody(ctx context.Context, request *http1.Request) (*emptypb.Empty, error) {
	req := &emptypb.Empty{}
	ok, err := server.CustomDecodeRequest(ctx, request, req)
	if err != nil {
		return nil, err
	}
	if ok {
		return req, nil
	}
	return req, nil
}
func (decoder bodyRequestDecoder) HttpBodyStarBody(ctx context.Context, request *http1.Request) (*httpbody.HttpBody, error) {
	req := &httpbody.HttpBody{}
	ok, err := server.CustomDecodeRequest(ctx, request, req)
	if err != nil {
		return nil, err
	}
	if ok {
		return req, nil
	}
	if err := server.DecodeHttpBody(ctx, request, req); err != nil {
		return nil, err
	}
	return req, nil
}
func (decoder bodyRequestDecoder) HttpBodyNamedBody(ctx context.Context, request *http1.Request) (*HttpBodyRequest, error) {
	req := &HttpBodyRequest{}
	ok, err := server.CustomDecodeRequest(ctx, request, req)
	if err != nil {
		return nil, err
	}
	if ok {
		return req, nil
	}
	if req.Body == nil {
		req.Body = &httpbody.HttpBody{}
	}
	if err := server.DecodeHttpBody(ctx, request, req.Body); err != nil {
		return nil, err
	}
	return req, nil
}
func (decoder bodyRequestDecoder) HttpRequest(ctx context.Context, request *http1.Request) (*http.HttpRequest, error) {
	req := &http.HttpRequest{}
	ok, err := server.CustomDecodeRequest(ctx, request, req)
	if err != nil {
		return nil, err
	}
	if ok {
		return req, nil
	}
	if err := server.DecodeHttpRequest(ctx, request, req); err != nil {
		return nil, err
	}
	return req, nil
}

type bodyResponseEncoder struct {
	marshalOptions   protojson.MarshalOptions
	unmarshalOptions protojson.UnmarshalOptions
}

func (encoder bodyResponseEncoder) StarBody(ctx context.Context, w http1.ResponseWriter, resp *Response) error {
	return server.EncodeResponse(ctx, w, resp, encoder.marshalOptions)
}
func (encoder bodyResponseEncoder) NamedBody(ctx context.Context, w http1.ResponseWriter, resp *Response) error {
	return server.EncodeResponse(ctx, w, resp, encoder.marshalOptions)
}
func (encoder bodyResponseEncoder) NonBody(ctx context.Context, w http1.ResponseWriter, resp *Response) error {
	return server.EncodeResponse(ctx, w, resp, encoder.marshalOptions)
}
func (encoder bodyResponseEncoder) HttpBodyStarBody(ctx context.Context, w http1.ResponseWriter, resp *Response) error {
	return server.EncodeResponse(ctx, w, resp, encoder.marshalOptions)
}
func (encoder bodyResponseEncoder) HttpBodyNamedBody(ctx context.Context, w http1.ResponseWriter, resp *Response) error {
	return server.EncodeResponse(ctx, w, resp, encoder.marshalOptions)
}
func (encoder bodyResponseEncoder) HttpRequest(ctx context.Context, w http1.ResponseWriter, resp *Response) error {
	return server.EncodeResponse(ctx, w, resp, encoder.marshalOptions)
}

func NewBodyHttpClient(target string, opts ...client.Option) BodyService {
	options := client.NewOptions(opts...)
	client := &bodyHttpClient{
		client: options.Client(),
		encoder: bodyRequestEncoder{
			target:         target,
			marshalOptions: options.MarshalOptions(),
			resolver:       options.Resolver(),
		},
		decoder: bodyResponseDecoder{
			unmarshalOptions: options.UnmarshalOptions(),
			errorDecoder:     options.ErrorDecoder(),
			errorFactory:     options.ErrorFactory(),
		},
		shouldFailFast:          options.ShouldFailFast(),
		onValidationErrCallback: options.OnValidationErrCallback(),
		middleware:              client.Chain(options.Middlewares()...),
	}
	return client
}

type bodyHttpClient struct {
	client                  *http1.Client
	encoder                 bodyRequestEncoder
	decoder                 bodyResponseDecoder
	shouldFailFast          bool
	onValidationErrCallback goose.OnValidationErrCallback
	middleware              client.Middleware
}

func (c *bodyHttpClient) StarBody(ctx context.Context, req *BodyRequest) (*Response, error) {
	if err := goose.ValidateRequest(ctx, req, c.shouldFailFast, c.onValidationErrCallback); err != nil {
		return nil, err
	}
	request, err := c.encoder.StarBody(ctx, req)
	if err != nil {
		return nil, err
	}
	response, err := client.Invoke(c.middleware, c.client, request, _leo_goose_example_body_v1_Body_StarBody_Desc.RouteInfo)
	if err != nil {
		return nil, err
	}
	resp, err := c.decoder.StarBody(ctx, response)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *bodyHttpClient) NamedBody(ctx context.Context, req *NamedBodyRequest) (*Response, error) {
	if err := goose.ValidateRequest(ctx, req, c.shouldFailFast, c.onValidationErrCallback); err != nil {
		return nil, err
	}
	request, err := c.encoder.NamedBody(ctx, req)
	if err != nil {
		return nil, err
	}
	response, err := client.Invoke(c.middleware, c.client, request, _leo_goose_example_body_v1_Body_NamedBody_Desc.RouteInfo)
	if err != nil {
		return nil, err
	}
	resp, err := c.decoder.NamedBody(ctx, response)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *bodyHttpClient) NonBody(ctx context.Context, req *emptypb.Empty) (*Response, error) {
	if err := goose.ValidateRequest(ctx, req, c.shouldFailFast, c.onValidationErrCallback); err != nil {
		return nil, err
	}
	request, err := c.encoder.NonBody(ctx, req)
	if err != nil {
		return nil, err
	}
	response, err := client.Invoke(c.middleware, c.client, request, _leo_goose_example_body_v1_Body_NonBody_Desc.RouteInfo)
	if err != nil {
		return nil, err
	}
	resp, err := c.decoder.NonBody(ctx, response)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *bodyHttpClient) HttpBodyStarBody(ctx context.Context, req *httpbody.HttpBody) (*Response, error) {
	if err := goose.ValidateRequest(ctx, req, c.shouldFailFast, c.onValidationErrCallback); err != nil {
		return nil, err
	}
	request, err := c.encoder.HttpBodyStarBody(ctx, req)
	if err != nil {
		return nil, err
	}
	response, err := client.Invoke(c.middleware, c.client, request, _leo_goose_example_body_v1_Body_HttpBodyStarBody_Desc.RouteInfo)
	if err != nil {
		return nil, err
	}
	resp, err := c.decoder.HttpBodyStarBody(ctx, response)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *bodyHttpClient) HttpBodyNamedBody(ctx context.Context, req *HttpBodyRequest) (*Response, error) {
	if err := goose.ValidateRequest(ctx, req, c.shouldFailFast, c.onValidationErrCallback); err != nil {
		return nil, err
	}
	request, err := c.encoder.HttpBodyNamedBody(ctx, req)
	if err != nil {
		return nil, err
	}
	response, err := client.Invoke(c.middleware, c.client, request, _leo_goose_example_body_v1_Body_HttpBodyNamedBody_Desc.RouteInfo)
	if err != nil {
		return nil, err
	}
	resp, err := c.decoder.HttpBodyNamedBody(ctx, response)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *bodyHttpClient) HttpRequest(ctx context.Context, req *http.HttpRequest) (*Response, error) {
	if err := goose.ValidateRequest(ctx, req, c.shouldFailFast, c.onValidationErrCallback); err != nil {
		return nil, err
	}
	request, err := c.encoder.HttpRequest(ctx, req)
	if err != nil {
		return nil, err
	}
	response, err := client.Invoke(c.middleware, c.client, request, _leo_goose_example_body_v1_Body_HttpRequest_Desc.RouteInfo)
	if err != nil {
		return nil, err
	}
	resp, err := c.decoder.HttpRequest(ctx, response)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

type bodyRequestEncoder struct {
	target         string
	marshalOptions protojson.MarshalOptions
	resolver       resolver.Resolver
}

func (encoder *bodyRequestEncoder) StarBody(ctx context.Context, req *BodyRequest) (*http1.Request, error) {
	if req == nil {
		return nil, errors.New("request is nil")
	}
	target, err := resolver.Resolve(ctx, encoder.resolver, encoder.target)
	if err != nil {
		return nil, err
	}
	method := "POST"
	header := http1.Header{}
	var body bytes.Buffer
	if err := client.EncodeMessage(ctx, req, header, &body, encoder.marshalOptions); err != nil {
		return nil, err
	}
	path := "/v1/star/body"
	target.Path = path
	request, err := http1.NewRequestWithContext(ctx, method, target.String(), &body)
	if err != nil {
		return nil, err
	}
	goose.CopyHeader(request.Header, header)
	return request, nil
}

func (encoder *bodyRequestEncoder) NamedBody(ctx context.Context, req *NamedBodyRequest) (*http1.Request, error) {
	if req == nil {
		return nil, errors.New("request is nil")
	}
	target, err := resolver.Resolve(ctx, encoder.resolver, encoder.target)
	if err != nil {
		return nil, err
	}
	method := "POST"
	header := http1.Header{}
	var body bytes.Buffer
	if err := client.EncodeMessage(ctx, req.GetBody(), header, &body, encoder.marshalOptions); err != nil {
		return nil, err
	}
	path := "/v1/named/body"
	target.Path = path
	request, err := http1.NewRequestWithContext(ctx, method, target.String(), &body)
	if err != nil {
		return nil, err
	}
	goose.CopyHeader(request.Header, header)
	return request, nil
}

func (encoder *bodyRequestEncoder) NonBody(ctx context.Context, req *emptypb.Empty) (*http1.Request, error) {
	if req == nil {
		return nil, errors.New("request is nil")
	}
	target, err := resolver.Resolve(ctx, encoder.resolver, encoder.target)
	if err != nil {
		return nil, err
	}
	method := "GET"
	header := http1.Header{}
	var body bytes.Buffer
	path := "/v1/user_body"
	target.Path = path
	request, err := http1.NewRequestWithContext(ctx, method, target.String(), &body)
	if err != nil {
		return nil, err
	}
	goose.CopyHeader(request.Header, header)
	return request, nil
}

func (encoder *bodyRequestEncoder) HttpBodyStarBody(ctx context.Context, req *httpbody.HttpBody) (*http1.Request, error) {
	if req == nil {
		return nil, errors.New("request is nil")
	}
	target, err := resolver.Resolve(ctx, encoder.resolver, encoder.target)
	if err != nil {
		return nil, err
	}
	method := "PUT"
	header := http1.Header{}
	var body bytes.Buffer
	if err := client.EncodeHttpBody(ctx, req, header, &body); err != nil {
		return nil, err
	}
	path := "/v1/http/body/star/body"
	target.Path = path
	request, err := http1.NewRequestWithContext(ctx, method, target.String(), &body)
	if err != nil {
		return nil, err
	}
	goose.CopyHeader(request.Header, header)
	return request, nil
}

func (encoder *bodyRequestEncoder) HttpBodyNamedBody(ctx context.Context, req *HttpBodyRequest) (*http1.Request, error) {
	if req == nil {
		return nil, errors.New("request is nil")
	}
	target, err := resolver.Resolve(ctx, encoder.resolver, encoder.target)
	if err != nil {
		return nil, err
	}
	method := "PUT"
	header := http1.Header{}
	var body bytes.Buffer
	if err := client.EncodeHttpBody(ctx, req.GetBody(), header, &body); err != nil {
		return nil, err
	}
	path := "/v1/http/body/named/body"
	target.Path = path
	request, err := http1.NewRequestWithContext(ctx, method, target.String(), &body)
	if err != nil {
		return nil, err
	}
	goose.CopyHeader(request.Header, header)
	return request, nil
}

func (encoder *bodyRequestEncoder) HttpRequest(ctx context.Context, req *http.HttpRequest) (*http1.Request, error) {
	if req == nil {
		return nil, errors.New("request is nil")
	}
	target, err := resolver.Resolve(ctx, encoder.resolver, encoder.target)
	if err != nil {
		return nil, err
	}
	method := "PUT"
	header := http1.Header{}
	var body bytes.Buffer
	if err := client.EncodeHttpRequest(ctx, req, header, &body); err != nil {
		return nil, err
	}
	path := "/v1/http/request"
	target.Path = path
	request, err := http1.NewRequestWithContext(ctx, method, target.String(), &body)
	if err != nil {
		return nil, err
	}
	goose.CopyHeader(request.Header, header)
	return request, nil
}

type bodyResponseDecoder struct {
	unmarshalOptions protojson.UnmarshalOptions
	errorDecoder     goose.ErrorDecoder
	errorFactory     goose.ErrorFactory
}

func (decoder *bodyResponseDecoder) StarBody(ctx context.Context, response *http1.Response) (*Response, error) {
	if respErr, ok := decoder.errorDecoder(ctx, response, decoder.errorFactory); ok {
		return nil, respErr
	}
	resp := &Response{}
	if err := client.DecodeMessage(ctx, response, resp, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	return resp, nil
}

func (decoder *bodyResponseDecoder) NamedBody(ctx context.Context, response *http1.Response) (*Response, error) {
	if respErr, ok := decoder.errorDecoder(ctx, response, decoder.errorFactory); ok {
		return nil, respErr
	}
	resp := &Response{}
	if err := client.DecodeMessage(ctx, response, resp, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	return resp, nil
}

func (decoder *bodyResponseDecoder) NonBody(ctx context.Context, response *http1.Response) (*Response, error) {
	if respErr, ok := decoder.errorDecoder(ctx, response, decoder.errorFactory); ok {
		return nil, respErr
	}
	resp := &Response{}
	if err := client.DecodeMessage(ctx, response, resp, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	return resp, nil
}

func (decoder *bodyResponseDecoder) HttpBodyStarBody(ctx context.Context, response *http1.Response) (*Response, error) {
	if respErr, ok := decoder.errorDecoder(ctx, response, decoder.errorFactory); ok {
		return nil, respErr
	}
	resp := &Response{}
	if err := client.DecodeMessage(ctx, response, resp, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	return resp, nil
}

func (decoder *bodyResponseDecoder) HttpBodyNamedBody(ctx context.Context, response *http1.Response) (*Response, error) {
	if respErr, ok := decoder.errorDecoder(ctx, response, decoder.errorFactory); ok {
		return nil, respErr
	}
	resp := &Response{}
	if err := client.DecodeMessage(ctx, response, resp, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	return resp, nil
}

func (decoder *bodyResponseDecoder) HttpRequest(ctx context.Context, response *http1.Response) (*Response, error) {
	if respErr, ok := decoder.errorDecoder(ctx, response, decoder.errorFactory); ok {
		return nil, respErr
	}
	resp := &Response{}
	if err := client.DecodeMessage(ctx, response, resp, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	return resp, nil
}

var _leo_goose_example_body_v1_Body_StarBody_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "POST",
		Pattern:    "/v1/star/body",
		FullMethod: "/leo.goose.example.body.v1.Body/StarBody",
	},
}

var _leo_goose_example_body_v1_Body_NamedBody_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "POST",
		Pattern:    "/v1/named/body",
		FullMethod: "/leo.goose.example.body.v1.Body/NamedBody",
	},
}

var _leo_goose_example_body_v1_Body_NonBody_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "GET",
		Pattern:    "/v1/user_body",
		FullMethod: "/leo.goose.example.body.v1.Body/NonBody",
	},
}

var _leo_goose_example_body_v1_Body_HttpBodyStarBody_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "PUT",
		Pattern:    "/v1/http/body/star/body",
		FullMethod: "/leo.goose.example.body.v1.Body/HttpBodyStarBody",
	},
}

var _leo_goose_example_body_v1_Body_HttpBodyNamedBody_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "PUT",
		Pattern:    "/v1/http/body/named/body",
		FullMethod: "/leo.goose.example.body.v1.Body/HttpBodyNamedBody",
	},
}

var _leo_goose_example_body_v1_Body_HttpRequest_Desc = &goose.Desc{
	RouteInfo: &goose.RouteInfo{
		HttpMethod: "PUT",
		Pattern:    "/v1/http/request",
		FullMethod: "/leo.goose.example.body.v1.Body/HttpRequest",
	},
}
