// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: example/response_body/response_body.proto

package response_body

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	http "google.golang.org/genproto/googleapis/rpc/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_example_response_body_response_body_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_example_response_body_response_body_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_example_response_body_response_body_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_example_response_body_response_body_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_example_response_body_response_body_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_example_response_body_response_body_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NamedBodyResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Body          *NamedBodyResponse_Body `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedBodyResponse) Reset() {
	*x = NamedBodyResponse{}
	mi := &file_example_response_body_response_body_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedBodyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedBodyResponse) ProtoMessage() {}

func (x *NamedBodyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_response_body_response_body_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedBodyResponse.ProtoReflect.Descriptor instead.
func (*NamedBodyResponse) Descriptor() ([]byte, []int) {
	return file_example_response_body_response_body_proto_rawDescGZIP(), []int{2}
}

func (x *NamedBodyResponse) GetBody() *NamedBodyResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type NamedHttpBodyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *httpbody.HttpBody     `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedHttpBodyResponse) Reset() {
	*x = NamedHttpBodyResponse{}
	mi := &file_example_response_body_response_body_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedHttpBodyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedHttpBodyResponse) ProtoMessage() {}

func (x *NamedHttpBodyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_response_body_response_body_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedHttpBodyResponse.ProtoReflect.Descriptor instead.
func (*NamedHttpBodyResponse) Descriptor() ([]byte, []int) {
	return file_example_response_body_response_body_proto_rawDescGZIP(), []int{3}
}

func (x *NamedHttpBodyResponse) GetBody() *httpbody.HttpBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type NamedBodyResponse_Body struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedBodyResponse_Body) Reset() {
	*x = NamedBodyResponse_Body{}
	mi := &file_example_response_body_response_body_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedBodyResponse_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedBodyResponse_Body) ProtoMessage() {}

func (x *NamedBodyResponse_Body) ProtoReflect() protoreflect.Message {
	mi := &file_example_response_body_response_body_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedBodyResponse_Body.ProtoReflect.Descriptor instead.
func (*NamedBodyResponse_Body) Descriptor() ([]byte, []int) {
	return file_example_response_body_response_body_proto_rawDescGZIP(), []int{2, 0}
}

func (x *NamedBodyResponse_Body) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_example_response_body_response_body_proto protoreflect.FileDescriptor

const file_example_response_body_response_body_proto_rawDesc = "" +
	"\n" +
	")example/response_body/response_body.proto\x12\"leo.goose.example.response_body.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/httpbody.proto\x1a\x15google/rpc/http.proto\"#\n" +
	"\aRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x85\x01\n" +
	"\x11NamedBodyResponse\x12N\n" +
	"\x04body\x18\x01 \x01(\v2:.leo.goose.example.response_body.v1.NamedBodyResponse.BodyR\x04body\x1a \n" +
	"\x04Body\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"A\n" +
	"\x15NamedHttpBodyResponse\x12(\n" +
	"\x04body\x18\x01 \x01(\v2\x14.google.api.HttpBodyR\x04body2\xdc\x06\n" +
	"\fResponseBody\x12\x8a\x01\n" +
	"\x0fOmittedResponse\x12+.leo.goose.example.response_body.v1.Request\x1a,.leo.goose.example.response_body.v1.Response\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/omitted/response\x12\x87\x01\n" +
	"\fStarResponse\x12+.leo.goose.example.response_body.v1.Request\x1a,.leo.goose.example.response_body.v1.Response\"\x1c\x82\xd3\xe4\x93\x02\x16b\x01*\x12\x11/v1/star/response\x12\x95\x01\n" +
	"\rNamedResponse\x12+.leo.goose.example.response_body.v1.Request\x1a5.leo.goose.example.response_body.v1.NamedBodyResponse\" \x82\xd3\xe4\x93\x02\x1ab\x04body\x12\x12/v1/named/response\x12}\n" +
	"\x10HttpBodyResponse\x12+.leo.goose.example.response_body.v1.Request\x1a\x14.google.api.HttpBody\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/http/body/omitted/response\x12\xab\x01\n" +
	"\x15HttpBodyNamedResponse\x12+.leo.goose.example.response_body.v1.Request\x1a9.leo.goose.example.response_body.v1.NamedHttpBodyResponse\"*\x82\xd3\xe4\x93\x02$b\x04body\x12\x1c/v1/http/body/named/response\x12p\n" +
	"\fHttpResponse\x12+.leo.goose.example.response_body.v1.Request\x1a\x18.google.rpc.HttpResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/http/responseBAZ?github.com/soyacen/goose/example/response_body/v1;response_bodyb\x06proto3"

var (
	file_example_response_body_response_body_proto_rawDescOnce sync.Once
	file_example_response_body_response_body_proto_rawDescData []byte
)

func file_example_response_body_response_body_proto_rawDescGZIP() []byte {
	file_example_response_body_response_body_proto_rawDescOnce.Do(func() {
		file_example_response_body_response_body_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_response_body_response_body_proto_rawDesc), len(file_example_response_body_response_body_proto_rawDesc)))
	})
	return file_example_response_body_response_body_proto_rawDescData
}

var file_example_response_body_response_body_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_example_response_body_response_body_proto_goTypes = []any{
	(*Request)(nil),                // 0: leo.goose.example.response_body.v1.Request
	(*Response)(nil),               // 1: leo.goose.example.response_body.v1.Response
	(*NamedBodyResponse)(nil),      // 2: leo.goose.example.response_body.v1.NamedBodyResponse
	(*NamedHttpBodyResponse)(nil),  // 3: leo.goose.example.response_body.v1.NamedHttpBodyResponse
	(*NamedBodyResponse_Body)(nil), // 4: leo.goose.example.response_body.v1.NamedBodyResponse.Body
	(*httpbody.HttpBody)(nil),      // 5: google.api.HttpBody
	(*http.HttpResponse)(nil),      // 6: google.rpc.HttpResponse
}
var file_example_response_body_response_body_proto_depIdxs = []int32{
	4, // 0: leo.goose.example.response_body.v1.NamedBodyResponse.body:type_name -> leo.goose.example.response_body.v1.NamedBodyResponse.Body
	5, // 1: leo.goose.example.response_body.v1.NamedHttpBodyResponse.body:type_name -> google.api.HttpBody
	0, // 2: leo.goose.example.response_body.v1.ResponseBody.OmittedResponse:input_type -> leo.goose.example.response_body.v1.Request
	0, // 3: leo.goose.example.response_body.v1.ResponseBody.StarResponse:input_type -> leo.goose.example.response_body.v1.Request
	0, // 4: leo.goose.example.response_body.v1.ResponseBody.NamedResponse:input_type -> leo.goose.example.response_body.v1.Request
	0, // 5: leo.goose.example.response_body.v1.ResponseBody.HttpBodyResponse:input_type -> leo.goose.example.response_body.v1.Request
	0, // 6: leo.goose.example.response_body.v1.ResponseBody.HttpBodyNamedResponse:input_type -> leo.goose.example.response_body.v1.Request
	0, // 7: leo.goose.example.response_body.v1.ResponseBody.HttpResponse:input_type -> leo.goose.example.response_body.v1.Request
	1, // 8: leo.goose.example.response_body.v1.ResponseBody.OmittedResponse:output_type -> leo.goose.example.response_body.v1.Response
	1, // 9: leo.goose.example.response_body.v1.ResponseBody.StarResponse:output_type -> leo.goose.example.response_body.v1.Response
	2, // 10: leo.goose.example.response_body.v1.ResponseBody.NamedResponse:output_type -> leo.goose.example.response_body.v1.NamedBodyResponse
	5, // 11: leo.goose.example.response_body.v1.ResponseBody.HttpBodyResponse:output_type -> google.api.HttpBody
	3, // 12: leo.goose.example.response_body.v1.ResponseBody.HttpBodyNamedResponse:output_type -> leo.goose.example.response_body.v1.NamedHttpBodyResponse
	6, // 13: leo.goose.example.response_body.v1.ResponseBody.HttpResponse:output_type -> google.rpc.HttpResponse
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_example_response_body_response_body_proto_init() }
func file_example_response_body_response_body_proto_init() {
	if File_example_response_body_response_body_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_response_body_response_body_proto_rawDesc), len(file_example_response_body_response_body_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_response_body_response_body_proto_goTypes,
		DependencyIndexes: file_example_response_body_response_body_proto_depIdxs,
		MessageInfos:      file_example_response_body_response_body_proto_msgTypes,
	}.Build()
	File_example_response_body_response_body_proto = out.File
	file_example_response_body_response_body_proto_goTypes = nil
	file_example_response_body_response_body_proto_depIdxs = nil
}
