// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: example/query/query.proto

package query

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumQueryRequest_Status int32

const (
	EnumQueryRequest_UNKNOWN       EnumQueryRequest_Status = 0
	EnumQueryRequest_OK            EnumQueryRequest_Status = 1
	EnumQueryRequest_CANCELLED     EnumQueryRequest_Status = 2
	EnumQueryRequest_UNKNOWN_ERROR EnumQueryRequest_Status = 3
)

// Enum value maps for EnumQueryRequest_Status.
var (
	EnumQueryRequest_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "OK",
		2: "CANCELLED",
		3: "UNKNOWN_ERROR",
	}
	EnumQueryRequest_Status_value = map[string]int32{
		"UNKNOWN":       0,
		"OK":            1,
		"CANCELLED":     2,
		"UNKNOWN_ERROR": 3,
	}
)

func (x EnumQueryRequest_Status) Enum() *EnumQueryRequest_Status {
	p := new(EnumQueryRequest_Status)
	*p = x
	return p
}

func (x EnumQueryRequest_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumQueryRequest_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_example_query_query_proto_enumTypes[0].Descriptor()
}

func (EnumQueryRequest_Status) Type() protoreflect.EnumType {
	return &file_example_query_query_proto_enumTypes[0]
}

func (x EnumQueryRequest_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumQueryRequest_Status.Descriptor instead.
func (EnumQueryRequest_Status) EnumDescriptor() ([]byte, []int) {
	return file_example_query_query_proto_rawDescGZIP(), []int{8, 0}
}

type BoolQueryRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Bool          bool                    `protobuf:"varint,1,opt,name=bool,proto3" json:"bool,omitempty"`
	OptBool       *bool                   `protobuf:"varint,2,opt,name=opt_bool,json=optBool,proto3,oneof" json:"opt_bool,omitempty"`
	WrapBool      *wrapperspb.BoolValue   `protobuf:"bytes,3,opt,name=wrap_bool,json=wrapBool,proto3" json:"wrap_bool,omitempty"`
	ListBool      []bool                  `protobuf:"varint,4,rep,packed,name=list_bool,json=listBool,proto3" json:"list_bool,omitempty"`
	ListWrapBool  []*wrapperspb.BoolValue `protobuf:"bytes,5,rep,name=list_wrap_bool,json=listWrapBool,proto3" json:"list_wrap_bool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolQueryRequest) Reset() {
	*x = BoolQueryRequest{}
	mi := &file_example_query_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolQueryRequest) ProtoMessage() {}

func (x *BoolQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_query_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolQueryRequest.ProtoReflect.Descriptor instead.
func (*BoolQueryRequest) Descriptor() ([]byte, []int) {
	return file_example_query_query_proto_rawDescGZIP(), []int{0}
}

func (x *BoolQueryRequest) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *BoolQueryRequest) GetOptBool() bool {
	if x != nil && x.OptBool != nil {
		return *x.OptBool
	}
	return false
}

func (x *BoolQueryRequest) GetWrapBool() *wrapperspb.BoolValue {
	if x != nil {
		return x.WrapBool
	}
	return nil
}

func (x *BoolQueryRequest) GetListBool() []bool {
	if x != nil {
		return x.ListBool
	}
	return nil
}

func (x *BoolQueryRequest) GetListWrapBool() []*wrapperspb.BoolValue {
	if x != nil {
		return x.ListWrapBool
	}
	return nil
}

type Int32QueryRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Int32         int32                    `protobuf:"varint,1,opt,name=int32,proto3" json:"int32,omitempty"`
	Sint32        int32                    `protobuf:"zigzag32,2,opt,name=sint32,proto3" json:"sint32,omitempty"`
	Sfixed32      int32                    `protobuf:"fixed32,3,opt,name=sfixed32,proto3" json:"sfixed32,omitempty"`
	OptInt32      *int32                   `protobuf:"varint,4,opt,name=opt_int32,json=optInt32,proto3,oneof" json:"opt_int32,omitempty"`
	OptSint32     *int32                   `protobuf:"zigzag32,5,opt,name=opt_sint32,json=optSint32,proto3,oneof" json:"opt_sint32,omitempty"`
	OptSfixed32   *int32                   `protobuf:"fixed32,6,opt,name=opt_sfixed32,json=optSfixed32,proto3,oneof" json:"opt_sfixed32,omitempty"`
	WrapInt32     *wrapperspb.Int32Value   `protobuf:"bytes,7,opt,name=wrap_int32,json=wrapInt32,proto3" json:"wrap_int32,omitempty"`
	ListInt32     []int32                  `protobuf:"varint,8,rep,packed,name=list_int32,json=listInt32,proto3" json:"list_int32,omitempty"`
	ListSint32    []int32                  `protobuf:"zigzag32,9,rep,packed,name=list_sint32,json=listSint32,proto3" json:"list_sint32,omitempty"`
	ListSfixed32  []int32                  `protobuf:"fixed32,10,rep,packed,name=list_sfixed32,json=listSfixed32,proto3" json:"list_sfixed32,omitempty"`
	ListWrapInt32 []*wrapperspb.Int32Value `protobuf:"bytes,11,rep,name=list_wrap_int32,json=listWrapInt32,proto3" json:"list_wrap_int32,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int32QueryRequest) Reset() {
	*x = Int32QueryRequest{}
	mi := &file_example_query_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32QueryRequest) ProtoMessage() {}

func (x *Int32QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_query_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32QueryRequest.ProtoReflect.Descriptor instead.
func (*Int32QueryRequest) Descriptor() ([]byte, []int) {
	return file_example_query_query_proto_rawDescGZIP(), []int{1}
}

func (x *Int32QueryRequest) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *Int32QueryRequest) GetSint32() int32 {
	if x != nil {
		return x.Sint32
	}
	return 0
}

func (x *Int32QueryRequest) GetSfixed32() int32 {
	if x != nil {
		return x.Sfixed32
	}
	return 0
}

func (x *Int32QueryRequest) GetOptInt32() int32 {
	if x != nil && x.OptInt32 != nil {
		return *x.OptInt32
	}
	return 0
}

func (x *Int32QueryRequest) GetOptSint32() int32 {
	if x != nil && x.OptSint32 != nil {
		return *x.OptSint32
	}
	return 0
}

func (x *Int32QueryRequest) GetOptSfixed32() int32 {
	if x != nil && x.OptSfixed32 != nil {
		return *x.OptSfixed32
	}
	return 0
}

func (x *Int32QueryRequest) GetWrapInt32() *wrapperspb.Int32Value {
	if x != nil {
		return x.WrapInt32
	}
	return nil
}

func (x *Int32QueryRequest) GetListInt32() []int32 {
	if x != nil {
		return x.ListInt32
	}
	return nil
}

func (x *Int32QueryRequest) GetListSint32() []int32 {
	if x != nil {
		return x.ListSint32
	}
	return nil
}

func (x *Int32QueryRequest) GetListSfixed32() []int32 {
	if x != nil {
		return x.ListSfixed32
	}
	return nil
}

func (x *Int32QueryRequest) GetListWrapInt32() []*wrapperspb.Int32Value {
	if x != nil {
		return x.ListWrapInt32
	}
	return nil
}

type Int64QueryRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Int64         int64                    `protobuf:"varint,1,opt,name=int64,proto3" json:"int64,omitempty"`
	Sint64        int64                    `protobuf:"zigzag64,2,opt,name=sint64,proto3" json:"sint64,omitempty"`
	Sfixed64      int64                    `protobuf:"fixed64,3,opt,name=sfixed64,proto3" json:"sfixed64,omitempty"`
	OptInt64      *int64                   `protobuf:"varint,4,opt,name=opt_int64,json=optInt64,proto3,oneof" json:"opt_int64,omitempty"`
	OptSint64     *int64                   `protobuf:"zigzag64,5,opt,name=opt_sint64,json=optSint64,proto3,oneof" json:"opt_sint64,omitempty"`
	OptSfixed64   *int64                   `protobuf:"fixed64,6,opt,name=opt_sfixed64,json=optSfixed64,proto3,oneof" json:"opt_sfixed64,omitempty"`
	WrapInt64     *wrapperspb.Int64Value   `protobuf:"bytes,7,opt,name=wrap_int64,json=wrapInt64,proto3" json:"wrap_int64,omitempty"`
	ListInt64     []int64                  `protobuf:"varint,8,rep,packed,name=list_int64,json=listInt64,proto3" json:"list_int64,omitempty"`
	ListSint64    []int64                  `protobuf:"zigzag64,9,rep,packed,name=list_sint64,json=listSint64,proto3" json:"list_sint64,omitempty"`
	ListSfixed64  []int64                  `protobuf:"fixed64,10,rep,packed,name=list_sfixed64,json=listSfixed64,proto3" json:"list_sfixed64,omitempty"`
	ListWrapInt64 []*wrapperspb.Int64Value `protobuf:"bytes,11,rep,name=list_wrap_int64,json=listWrapInt64,proto3" json:"list_wrap_int64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int64QueryRequest) Reset() {
	*x = Int64QueryRequest{}
	mi := &file_example_query_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64QueryRequest) ProtoMessage() {}

func (x *Int64QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_query_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64QueryRequest.ProtoReflect.Descriptor instead.
func (*Int64QueryRequest) Descriptor() ([]byte, []int) {
	return file_example_query_query_proto_rawDescGZIP(), []int{2}
}

func (x *Int64QueryRequest) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

func (x *Int64QueryRequest) GetSint64() int64 {
	if x != nil {
		return x.Sint64
	}
	return 0
}

func (x *Int64QueryRequest) GetSfixed64() int64 {
	if x != nil {
		return x.Sfixed64
	}
	return 0
}

func (x *Int64QueryRequest) GetOptInt64() int64 {
	if x != nil && x.OptInt64 != nil {
		return *x.OptInt64
	}
	return 0
}

func (x *Int64QueryRequest) GetOptSint64() int64 {
	if x != nil && x.OptSint64 != nil {
		return *x.OptSint64
	}
	return 0
}

func (x *Int64QueryRequest) GetOptSfixed64() int64 {
	if x != nil && x.OptSfixed64 != nil {
		return *x.OptSfixed64
	}
	return 0
}

func (x *Int64QueryRequest) GetWrapInt64() *wrapperspb.Int64Value {
	if x != nil {
		return x.WrapInt64
	}
	return nil
}

func (x *Int64QueryRequest) GetListInt64() []int64 {
	if x != nil {
		return x.ListInt64
	}
	return nil
}

func (x *Int64QueryRequest) GetListSint64() []int64 {
	if x != nil {
		return x.ListSint64
	}
	return nil
}

func (x *Int64QueryRequest) GetListSfixed64() []int64 {
	if x != nil {
		return x.ListSfixed64
	}
	return nil
}

func (x *Int64QueryRequest) GetListWrapInt64() []*wrapperspb.Int64Value {
	if x != nil {
		return x.ListWrapInt64
	}
	return nil
}

type Uint32QueryRequest struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	Uint32         uint32                    `protobuf:"varint,1,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Fixed32        uint32                    `protobuf:"fixed32,2,opt,name=fixed32,proto3" json:"fixed32,omitempty"`
	OptUint32      *uint32                   `protobuf:"varint,3,opt,name=opt_uint32,json=optUint32,proto3,oneof" json:"opt_uint32,omitempty"`
	OptFixed32     *uint32                   `protobuf:"fixed32,4,opt,name=opt_fixed32,json=optFixed32,proto3,oneof" json:"opt_fixed32,omitempty"`
	WrapUint32     *wrapperspb.UInt32Value   `protobuf:"bytes,5,opt,name=wrap_uint32,json=wrapUint32,proto3" json:"wrap_uint32,omitempty"`
	ListUint32     []uint32                  `protobuf:"varint,6,rep,packed,name=list_uint32,json=listUint32,proto3" json:"list_uint32,omitempty"`
	ListFixed32    []uint32                  `protobuf:"fixed32,7,rep,packed,name=list_fixed32,json=listFixed32,proto3" json:"list_fixed32,omitempty"`
	ListWrapUint32 []*wrapperspb.UInt32Value `protobuf:"bytes,8,rep,name=list_wrap_uint32,json=listWrapUint32,proto3" json:"list_wrap_uint32,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Uint32QueryRequest) Reset() {
	*x = Uint32QueryRequest{}
	mi := &file_example_query_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uint32QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint32QueryRequest) ProtoMessage() {}

func (x *Uint32QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_query_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint32QueryRequest.ProtoReflect.Descriptor instead.
func (*Uint32QueryRequest) Descriptor() ([]byte, []int) {
	return file_example_query_query_proto_rawDescGZIP(), []int{3}
}

func (x *Uint32QueryRequest) GetUint32() uint32 {
	if x != nil {
		return x.Uint32
	}
	return 0
}

func (x *Uint32QueryRequest) GetFixed32() uint32 {
	if x != nil {
		return x.Fixed32
	}
	return 0
}

func (x *Uint32QueryRequest) GetOptUint32() uint32 {
	if x != nil && x.OptUint32 != nil {
		return *x.OptUint32
	}
	return 0
}

func (x *Uint32QueryRequest) GetOptFixed32() uint32 {
	if x != nil && x.OptFixed32 != nil {
		return *x.OptFixed32
	}
	return 0
}

func (x *Uint32QueryRequest) GetWrapUint32() *wrapperspb.UInt32Value {
	if x != nil {
		return x.WrapUint32
	}
	return nil
}

func (x *Uint32QueryRequest) GetListUint32() []uint32 {
	if x != nil {
		return x.ListUint32
	}
	return nil
}

func (x *Uint32QueryRequest) GetListFixed32() []uint32 {
	if x != nil {
		return x.ListFixed32
	}
	return nil
}

func (x *Uint32QueryRequest) GetListWrapUint32() []*wrapperspb.UInt32Value {
	if x != nil {
		return x.ListWrapUint32
	}
	return nil
}

type Uint64QueryRequest struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	Uint64         uint64                    `protobuf:"varint,1,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Fixed64        uint64                    `protobuf:"fixed64,2,opt,name=fixed64,proto3" json:"fixed64,omitempty"`
	OptUint64      *uint64                   `protobuf:"varint,3,opt,name=opt_uint64,json=optUint64,proto3,oneof" json:"opt_uint64,omitempty"`
	OptFixed64     *uint64                   `protobuf:"fixed64,4,opt,name=opt_fixed64,json=optFixed64,proto3,oneof" json:"opt_fixed64,omitempty"`
	WrapUint64     *wrapperspb.UInt64Value   `protobuf:"bytes,5,opt,name=wrap_uint64,json=wrapUint64,proto3" json:"wrap_uint64,omitempty"`
	ListUint64     []uint64                  `protobuf:"varint,6,rep,packed,name=list_uint64,json=listUint64,proto3" json:"list_uint64,omitempty"`
	ListFixed64    []uint64                  `protobuf:"fixed64,7,rep,packed,name=list_fixed64,json=listFixed64,proto3" json:"list_fixed64,omitempty"`
	ListWrapUint64 []*wrapperspb.UInt64Value `protobuf:"bytes,8,rep,name=list_wrap_uint64,json=listWrapUint64,proto3" json:"list_wrap_uint64,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Uint64QueryRequest) Reset() {
	*x = Uint64QueryRequest{}
	mi := &file_example_query_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uint64QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint64QueryRequest) ProtoMessage() {}

func (x *Uint64QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_query_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint64QueryRequest.ProtoReflect.Descriptor instead.
func (*Uint64QueryRequest) Descriptor() ([]byte, []int) {
	return file_example_query_query_proto_rawDescGZIP(), []int{4}
}

func (x *Uint64QueryRequest) GetUint64() uint64 {
	if x != nil {
		return x.Uint64
	}
	return 0
}

func (x *Uint64QueryRequest) GetFixed64() uint64 {
	if x != nil {
		return x.Fixed64
	}
	return 0
}

func (x *Uint64QueryRequest) GetOptUint64() uint64 {
	if x != nil && x.OptUint64 != nil {
		return *x.OptUint64
	}
	return 0
}

func (x *Uint64QueryRequest) GetOptFixed64() uint64 {
	if x != nil && x.OptFixed64 != nil {
		return *x.OptFixed64
	}
	return 0
}

func (x *Uint64QueryRequest) GetWrapUint64() *wrapperspb.UInt64Value {
	if x != nil {
		return x.WrapUint64
	}
	return nil
}

func (x *Uint64QueryRequest) GetListUint64() []uint64 {
	if x != nil {
		return x.ListUint64
	}
	return nil
}

func (x *Uint64QueryRequest) GetListFixed64() []uint64 {
	if x != nil {
		return x.ListFixed64
	}
	return nil
}

func (x *Uint64QueryRequest) GetListWrapUint64() []*wrapperspb.UInt64Value {
	if x != nil {
		return x.ListWrapUint64
	}
	return nil
}

type FloatQueryRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Float         float32                  `protobuf:"fixed32,1,opt,name=float,proto3" json:"float,omitempty"`
	OptFloat      *float32                 `protobuf:"fixed32,2,opt,name=opt_float,json=optFloat,proto3,oneof" json:"opt_float,omitempty"`
	WrapFloat     *wrapperspb.FloatValue   `protobuf:"bytes,3,opt,name=wrap_float,json=wrapFloat,proto3" json:"wrap_float,omitempty"`
	ListFloat     []float32                `protobuf:"fixed32,4,rep,packed,name=list_float,json=listFloat,proto3" json:"list_float,omitempty"`
	ListWrapFloat []*wrapperspb.FloatValue `protobuf:"bytes,5,rep,name=list_wrap_float,json=listWrapFloat,proto3" json:"list_wrap_float,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatQueryRequest) Reset() {
	*x = FloatQueryRequest{}
	mi := &file_example_query_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatQueryRequest) ProtoMessage() {}

func (x *FloatQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_query_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatQueryRequest.ProtoReflect.Descriptor instead.
func (*FloatQueryRequest) Descriptor() ([]byte, []int) {
	return file_example_query_query_proto_rawDescGZIP(), []int{5}
}

func (x *FloatQueryRequest) GetFloat() float32 {
	if x != nil {
		return x.Float
	}
	return 0
}

func (x *FloatQueryRequest) GetOptFloat() float32 {
	if x != nil && x.OptFloat != nil {
		return *x.OptFloat
	}
	return 0
}

func (x *FloatQueryRequest) GetWrapFloat() *wrapperspb.FloatValue {
	if x != nil {
		return x.WrapFloat
	}
	return nil
}

func (x *FloatQueryRequest) GetListFloat() []float32 {
	if x != nil {
		return x.ListFloat
	}
	return nil
}

func (x *FloatQueryRequest) GetListWrapFloat() []*wrapperspb.FloatValue {
	if x != nil {
		return x.ListWrapFloat
	}
	return nil
}

type DoubleQueryRequest struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	Double         float64                   `protobuf:"fixed64,1,opt,name=double,proto3" json:"double,omitempty"`
	OptDouble      *float64                  `protobuf:"fixed64,2,opt,name=opt_double,json=optDouble,proto3,oneof" json:"opt_double,omitempty"`
	WrapDouble     *wrapperspb.DoubleValue   `protobuf:"bytes,3,opt,name=wrap_double,json=wrapDouble,proto3" json:"wrap_double,omitempty"`
	ListDouble     []float64                 `protobuf:"fixed64,4,rep,packed,name=list_double,json=listDouble,proto3" json:"list_double,omitempty"`
	ListWrapDouble []*wrapperspb.DoubleValue `protobuf:"bytes,5,rep,name=list_wrap_double,json=listWrapDouble,proto3" json:"list_wrap_double,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DoubleQueryRequest) Reset() {
	*x = DoubleQueryRequest{}
	mi := &file_example_query_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleQueryRequest) ProtoMessage() {}

func (x *DoubleQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_query_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleQueryRequest.ProtoReflect.Descriptor instead.
func (*DoubleQueryRequest) Descriptor() ([]byte, []int) {
	return file_example_query_query_proto_rawDescGZIP(), []int{6}
}

func (x *DoubleQueryRequest) GetDouble() float64 {
	if x != nil {
		return x.Double
	}
	return 0
}

func (x *DoubleQueryRequest) GetOptDouble() float64 {
	if x != nil && x.OptDouble != nil {
		return *x.OptDouble
	}
	return 0
}

func (x *DoubleQueryRequest) GetWrapDouble() *wrapperspb.DoubleValue {
	if x != nil {
		return x.WrapDouble
	}
	return nil
}

func (x *DoubleQueryRequest) GetListDouble() []float64 {
	if x != nil {
		return x.ListDouble
	}
	return nil
}

func (x *DoubleQueryRequest) GetListWrapDouble() []*wrapperspb.DoubleValue {
	if x != nil {
		return x.ListWrapDouble
	}
	return nil
}

type StringQueryRequest struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	String_        string                    `protobuf:"bytes,1,opt,name=string,proto3" json:"string,omitempty"`
	OptString      *string                   `protobuf:"bytes,2,opt,name=opt_string,json=optString,proto3,oneof" json:"opt_string,omitempty"`
	WrapString     *wrapperspb.StringValue   `protobuf:"bytes,3,opt,name=wrap_string,json=wrapString,proto3" json:"wrap_string,omitempty"`
	ListString     []string                  `protobuf:"bytes,4,rep,name=list_string,json=listString,proto3" json:"list_string,omitempty"`
	ListWrapString []*wrapperspb.StringValue `protobuf:"bytes,5,rep,name=list_wrap_string,json=listWrapString,proto3" json:"list_wrap_string,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StringQueryRequest) Reset() {
	*x = StringQueryRequest{}
	mi := &file_example_query_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringQueryRequest) ProtoMessage() {}

func (x *StringQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_query_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringQueryRequest.ProtoReflect.Descriptor instead.
func (*StringQueryRequest) Descriptor() ([]byte, []int) {
	return file_example_query_query_proto_rawDescGZIP(), []int{7}
}

func (x *StringQueryRequest) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *StringQueryRequest) GetOptString() string {
	if x != nil && x.OptString != nil {
		return *x.OptString
	}
	return ""
}

func (x *StringQueryRequest) GetWrapString() *wrapperspb.StringValue {
	if x != nil {
		return x.WrapString
	}
	return nil
}

func (x *StringQueryRequest) GetListString() []string {
	if x != nil {
		return x.ListString
	}
	return nil
}

func (x *StringQueryRequest) GetListWrapString() []*wrapperspb.StringValue {
	if x != nil {
		return x.ListWrapString
	}
	return nil
}

type EnumQueryRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        EnumQueryRequest_Status   `protobuf:"varint,1,opt,name=status,proto3,enum=leo.goose.example.query.v1.EnumQueryRequest_Status" json:"status,omitempty"`
	OptStatus     *EnumQueryRequest_Status  `protobuf:"varint,2,opt,name=opt_status,json=optStatus,proto3,enum=leo.goose.example.query.v1.EnumQueryRequest_Status,oneof" json:"opt_status,omitempty"`
	ListStatus    []EnumQueryRequest_Status `protobuf:"varint,3,rep,packed,name=list_status,json=listStatus,proto3,enum=leo.goose.example.query.v1.EnumQueryRequest_Status" json:"list_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumQueryRequest) Reset() {
	*x = EnumQueryRequest{}
	mi := &file_example_query_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumQueryRequest) ProtoMessage() {}

func (x *EnumQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_query_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumQueryRequest.ProtoReflect.Descriptor instead.
func (*EnumQueryRequest) Descriptor() ([]byte, []int) {
	return file_example_query_query_proto_rawDescGZIP(), []int{8}
}

func (x *EnumQueryRequest) GetStatus() EnumQueryRequest_Status {
	if x != nil {
		return x.Status
	}
	return EnumQueryRequest_UNKNOWN
}

func (x *EnumQueryRequest) GetOptStatus() EnumQueryRequest_Status {
	if x != nil && x.OptStatus != nil {
		return *x.OptStatus
	}
	return EnumQueryRequest_UNKNOWN
}

func (x *EnumQueryRequest) GetListStatus() []EnumQueryRequest_Status {
	if x != nil {
		return x.ListStatus
	}
	return nil
}

var File_example_query_query_proto protoreflect.FileDescriptor

const file_example_query_query_proto_rawDesc = "" +
	"\n" +
	"\x19example/query/query.proto\x12\x1aleo.goose.example.query.v1\x1a\x19google/api/httpbody.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xeb\x01\n" +
	"\x10BoolQueryRequest\x12\x12\n" +
	"\x04bool\x18\x01 \x01(\bR\x04bool\x12\x1e\n" +
	"\bopt_bool\x18\x02 \x01(\bH\x00R\aoptBool\x88\x01\x01\x127\n" +
	"\twrap_bool\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\bwrapBool\x12\x1b\n" +
	"\tlist_bool\x18\x04 \x03(\bR\blistBool\x12@\n" +
	"\x0elist_wrap_bool\x18\x05 \x03(\v2\x1a.google.protobuf.BoolValueR\flistWrapBoolB\v\n" +
	"\t_opt_bool\"\xdf\x03\n" +
	"\x11Int32QueryRequest\x12\x14\n" +
	"\x05int32\x18\x01 \x01(\x05R\x05int32\x12\x16\n" +
	"\x06sint32\x18\x02 \x01(\x11R\x06sint32\x12\x1a\n" +
	"\bsfixed32\x18\x03 \x01(\x0fR\bsfixed32\x12 \n" +
	"\topt_int32\x18\x04 \x01(\x05H\x00R\boptInt32\x88\x01\x01\x12\"\n" +
	"\n" +
	"opt_sint32\x18\x05 \x01(\x11H\x01R\toptSint32\x88\x01\x01\x12&\n" +
	"\fopt_sfixed32\x18\x06 \x01(\x0fH\x02R\voptSfixed32\x88\x01\x01\x12:\n" +
	"\n" +
	"wrap_int32\x18\a \x01(\v2\x1b.google.protobuf.Int32ValueR\twrapInt32\x12\x1d\n" +
	"\n" +
	"list_int32\x18\b \x03(\x05R\tlistInt32\x12\x1f\n" +
	"\vlist_sint32\x18\t \x03(\x11R\n" +
	"listSint32\x12#\n" +
	"\rlist_sfixed32\x18\n" +
	" \x03(\x0fR\flistSfixed32\x12C\n" +
	"\x0flist_wrap_int32\x18\v \x03(\v2\x1b.google.protobuf.Int32ValueR\rlistWrapInt32B\f\n" +
	"\n" +
	"_opt_int32B\r\n" +
	"\v_opt_sint32B\x0f\n" +
	"\r_opt_sfixed32\"\xdf\x03\n" +
	"\x11Int64QueryRequest\x12\x14\n" +
	"\x05int64\x18\x01 \x01(\x03R\x05int64\x12\x16\n" +
	"\x06sint64\x18\x02 \x01(\x12R\x06sint64\x12\x1a\n" +
	"\bsfixed64\x18\x03 \x01(\x10R\bsfixed64\x12 \n" +
	"\topt_int64\x18\x04 \x01(\x03H\x00R\boptInt64\x88\x01\x01\x12\"\n" +
	"\n" +
	"opt_sint64\x18\x05 \x01(\x12H\x01R\toptSint64\x88\x01\x01\x12&\n" +
	"\fopt_sfixed64\x18\x06 \x01(\x10H\x02R\voptSfixed64\x88\x01\x01\x12:\n" +
	"\n" +
	"wrap_int64\x18\a \x01(\v2\x1b.google.protobuf.Int64ValueR\twrapInt64\x12\x1d\n" +
	"\n" +
	"list_int64\x18\b \x03(\x03R\tlistInt64\x12\x1f\n" +
	"\vlist_sint64\x18\t \x03(\x12R\n" +
	"listSint64\x12#\n" +
	"\rlist_sfixed64\x18\n" +
	" \x03(\x10R\flistSfixed64\x12C\n" +
	"\x0flist_wrap_int64\x18\v \x03(\v2\x1b.google.protobuf.Int64ValueR\rlistWrapInt64B\f\n" +
	"\n" +
	"_opt_int64B\r\n" +
	"\v_opt_sint64B\x0f\n" +
	"\r_opt_sfixed64\"\xfa\x02\n" +
	"\x12Uint32QueryRequest\x12\x16\n" +
	"\x06uint32\x18\x01 \x01(\rR\x06uint32\x12\x18\n" +
	"\afixed32\x18\x02 \x01(\aR\afixed32\x12\"\n" +
	"\n" +
	"opt_uint32\x18\x03 \x01(\rH\x00R\toptUint32\x88\x01\x01\x12$\n" +
	"\vopt_fixed32\x18\x04 \x01(\aH\x01R\n" +
	"optFixed32\x88\x01\x01\x12=\n" +
	"\vwrap_uint32\x18\x05 \x01(\v2\x1c.google.protobuf.UInt32ValueR\n" +
	"wrapUint32\x12\x1f\n" +
	"\vlist_uint32\x18\x06 \x03(\rR\n" +
	"listUint32\x12!\n" +
	"\flist_fixed32\x18\a \x03(\aR\vlistFixed32\x12F\n" +
	"\x10list_wrap_uint32\x18\b \x03(\v2\x1c.google.protobuf.UInt32ValueR\x0elistWrapUint32B\r\n" +
	"\v_opt_uint32B\x0e\n" +
	"\f_opt_fixed32\"\xfa\x02\n" +
	"\x12Uint64QueryRequest\x12\x16\n" +
	"\x06uint64\x18\x01 \x01(\x04R\x06uint64\x12\x18\n" +
	"\afixed64\x18\x02 \x01(\x06R\afixed64\x12\"\n" +
	"\n" +
	"opt_uint64\x18\x03 \x01(\x04H\x00R\toptUint64\x88\x01\x01\x12$\n" +
	"\vopt_fixed64\x18\x04 \x01(\x06H\x01R\n" +
	"optFixed64\x88\x01\x01\x12=\n" +
	"\vwrap_uint64\x18\x05 \x01(\v2\x1c.google.protobuf.UInt64ValueR\n" +
	"wrapUint64\x12\x1f\n" +
	"\vlist_uint64\x18\x06 \x03(\x04R\n" +
	"listUint64\x12!\n" +
	"\flist_fixed64\x18\a \x03(\x06R\vlistFixed64\x12F\n" +
	"\x10list_wrap_uint64\x18\b \x03(\v2\x1c.google.protobuf.UInt64ValueR\x0elistWrapUint64B\r\n" +
	"\v_opt_uint64B\x0e\n" +
	"\f_opt_fixed64\"\xf9\x01\n" +
	"\x11FloatQueryRequest\x12\x14\n" +
	"\x05float\x18\x01 \x01(\x02R\x05float\x12 \n" +
	"\topt_float\x18\x02 \x01(\x02H\x00R\boptFloat\x88\x01\x01\x12:\n" +
	"\n" +
	"wrap_float\x18\x03 \x01(\v2\x1b.google.protobuf.FloatValueR\twrapFloat\x12\x1d\n" +
	"\n" +
	"list_float\x18\x04 \x03(\x02R\tlistFloat\x12C\n" +
	"\x0flist_wrap_float\x18\x05 \x03(\v2\x1b.google.protobuf.FloatValueR\rlistWrapFloatB\f\n" +
	"\n" +
	"_opt_float\"\x87\x02\n" +
	"\x12DoubleQueryRequest\x12\x16\n" +
	"\x06double\x18\x01 \x01(\x01R\x06double\x12\"\n" +
	"\n" +
	"opt_double\x18\x02 \x01(\x01H\x00R\toptDouble\x88\x01\x01\x12=\n" +
	"\vwrap_double\x18\x03 \x01(\v2\x1c.google.protobuf.DoubleValueR\n" +
	"wrapDouble\x12\x1f\n" +
	"\vlist_double\x18\x04 \x03(\x01R\n" +
	"listDouble\x12F\n" +
	"\x10list_wrap_double\x18\x05 \x03(\v2\x1c.google.protobuf.DoubleValueR\x0elistWrapDoubleB\r\n" +
	"\v_opt_double\"\x87\x02\n" +
	"\x12StringQueryRequest\x12\x16\n" +
	"\x06string\x18\x01 \x01(\tR\x06string\x12\"\n" +
	"\n" +
	"opt_string\x18\x02 \x01(\tH\x00R\toptString\x88\x01\x01\x12=\n" +
	"\vwrap_string\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"wrapString\x12\x1f\n" +
	"\vlist_string\x18\x04 \x03(\tR\n" +
	"listString\x12F\n" +
	"\x10list_wrap_string\x18\x05 \x03(\v2\x1c.google.protobuf.StringValueR\x0elistWrapStringB\r\n" +
	"\v_opt_string\"\xde\x02\n" +
	"\x10EnumQueryRequest\x12K\n" +
	"\x06status\x18\x01 \x01(\x0e23.leo.goose.example.query.v1.EnumQueryRequest.StatusR\x06status\x12W\n" +
	"\n" +
	"opt_status\x18\x02 \x01(\x0e23.leo.goose.example.query.v1.EnumQueryRequest.StatusH\x00R\toptStatus\x88\x01\x01\x12T\n" +
	"\vlist_status\x18\x03 \x03(\x0e23.leo.goose.example.query.v1.EnumQueryRequest.StatusR\n" +
	"listStatus\"?\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\r\n" +
	"\tCANCELLED\x10\x02\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x03B\r\n" +
	"\v_opt_status2n\n" +
	"\tBoolQuery\x12a\n" +
	"\tBoolQuery\x12,.leo.goose.example.query.v1.BoolQueryRequest\x1a\x14.google.api.HttpBody\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/bool2r\n" +
	"\n" +
	"Int32Query\x12d\n" +
	"\n" +
	"Int32Query\x12-.leo.goose.example.query.v1.Int32QueryRequest\x1a\x14.google.api.HttpBody\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/int322r\n" +
	"\n" +
	"Int64Query\x12d\n" +
	"\n" +
	"Int64Query\x12-.leo.goose.example.query.v1.Int64QueryRequest\x1a\x14.google.api.HttpBody\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/int642v\n" +
	"\vUint32Query\x12g\n" +
	"\vUint32Query\x12..leo.goose.example.query.v1.Uint32QueryRequest\x1a\x14.google.api.HttpBody\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/uint322v\n" +
	"\vUint64Query\x12g\n" +
	"\vUint64Query\x12..leo.goose.example.query.v1.Uint64QueryRequest\x1a\x14.google.api.HttpBody\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/uint642r\n" +
	"\n" +
	"FloatQuery\x12d\n" +
	"\n" +
	"FloatQuery\x12-.leo.goose.example.query.v1.FloatQueryRequest\x1a\x14.google.api.HttpBody\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/float2v\n" +
	"\vDoubleQuery\x12g\n" +
	"\vDoubleQuery\x12..leo.goose.example.query.v1.DoubleQueryRequest\x1a\x14.google.api.HttpBody\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/double2v\n" +
	"\vStringQuery\x12g\n" +
	"\vStringQuery\x12..leo.goose.example.query.v1.StringQueryRequest\x1a\x14.google.api.HttpBody\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/string2n\n" +
	"\tEnumQuery\x12a\n" +
	"\tEnumQuery\x12,.leo.goose.example.query.v1.EnumQueryRequest\x1a\x14.google.api.HttpBody\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/enumB1Z/github.com/soyacen/goose/example/query/v1;queryb\x06proto3"

var (
	file_example_query_query_proto_rawDescOnce sync.Once
	file_example_query_query_proto_rawDescData []byte
)

func file_example_query_query_proto_rawDescGZIP() []byte {
	file_example_query_query_proto_rawDescOnce.Do(func() {
		file_example_query_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_query_query_proto_rawDesc), len(file_example_query_query_proto_rawDesc)))
	})
	return file_example_query_query_proto_rawDescData
}

var file_example_query_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_example_query_query_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_example_query_query_proto_goTypes = []any{
	(EnumQueryRequest_Status)(0),   // 0: leo.goose.example.query.v1.EnumQueryRequest.Status
	(*BoolQueryRequest)(nil),       // 1: leo.goose.example.query.v1.BoolQueryRequest
	(*Int32QueryRequest)(nil),      // 2: leo.goose.example.query.v1.Int32QueryRequest
	(*Int64QueryRequest)(nil),      // 3: leo.goose.example.query.v1.Int64QueryRequest
	(*Uint32QueryRequest)(nil),     // 4: leo.goose.example.query.v1.Uint32QueryRequest
	(*Uint64QueryRequest)(nil),     // 5: leo.goose.example.query.v1.Uint64QueryRequest
	(*FloatQueryRequest)(nil),      // 6: leo.goose.example.query.v1.FloatQueryRequest
	(*DoubleQueryRequest)(nil),     // 7: leo.goose.example.query.v1.DoubleQueryRequest
	(*StringQueryRequest)(nil),     // 8: leo.goose.example.query.v1.StringQueryRequest
	(*EnumQueryRequest)(nil),       // 9: leo.goose.example.query.v1.EnumQueryRequest
	(*wrapperspb.BoolValue)(nil),   // 10: google.protobuf.BoolValue
	(*wrapperspb.Int32Value)(nil),  // 11: google.protobuf.Int32Value
	(*wrapperspb.Int64Value)(nil),  // 12: google.protobuf.Int64Value
	(*wrapperspb.UInt32Value)(nil), // 13: google.protobuf.UInt32Value
	(*wrapperspb.UInt64Value)(nil), // 14: google.protobuf.UInt64Value
	(*wrapperspb.FloatValue)(nil),  // 15: google.protobuf.FloatValue
	(*wrapperspb.DoubleValue)(nil), // 16: google.protobuf.DoubleValue
	(*wrapperspb.StringValue)(nil), // 17: google.protobuf.StringValue
	(*httpbody.HttpBody)(nil),      // 18: google.api.HttpBody
}
var file_example_query_query_proto_depIdxs = []int32{
	10, // 0: leo.goose.example.query.v1.BoolQueryRequest.wrap_bool:type_name -> google.protobuf.BoolValue
	10, // 1: leo.goose.example.query.v1.BoolQueryRequest.list_wrap_bool:type_name -> google.protobuf.BoolValue
	11, // 2: leo.goose.example.query.v1.Int32QueryRequest.wrap_int32:type_name -> google.protobuf.Int32Value
	11, // 3: leo.goose.example.query.v1.Int32QueryRequest.list_wrap_int32:type_name -> google.protobuf.Int32Value
	12, // 4: leo.goose.example.query.v1.Int64QueryRequest.wrap_int64:type_name -> google.protobuf.Int64Value
	12, // 5: leo.goose.example.query.v1.Int64QueryRequest.list_wrap_int64:type_name -> google.protobuf.Int64Value
	13, // 6: leo.goose.example.query.v1.Uint32QueryRequest.wrap_uint32:type_name -> google.protobuf.UInt32Value
	13, // 7: leo.goose.example.query.v1.Uint32QueryRequest.list_wrap_uint32:type_name -> google.protobuf.UInt32Value
	14, // 8: leo.goose.example.query.v1.Uint64QueryRequest.wrap_uint64:type_name -> google.protobuf.UInt64Value
	14, // 9: leo.goose.example.query.v1.Uint64QueryRequest.list_wrap_uint64:type_name -> google.protobuf.UInt64Value
	15, // 10: leo.goose.example.query.v1.FloatQueryRequest.wrap_float:type_name -> google.protobuf.FloatValue
	15, // 11: leo.goose.example.query.v1.FloatQueryRequest.list_wrap_float:type_name -> google.protobuf.FloatValue
	16, // 12: leo.goose.example.query.v1.DoubleQueryRequest.wrap_double:type_name -> google.protobuf.DoubleValue
	16, // 13: leo.goose.example.query.v1.DoubleQueryRequest.list_wrap_double:type_name -> google.protobuf.DoubleValue
	17, // 14: leo.goose.example.query.v1.StringQueryRequest.wrap_string:type_name -> google.protobuf.StringValue
	17, // 15: leo.goose.example.query.v1.StringQueryRequest.list_wrap_string:type_name -> google.protobuf.StringValue
	0,  // 16: leo.goose.example.query.v1.EnumQueryRequest.status:type_name -> leo.goose.example.query.v1.EnumQueryRequest.Status
	0,  // 17: leo.goose.example.query.v1.EnumQueryRequest.opt_status:type_name -> leo.goose.example.query.v1.EnumQueryRequest.Status
	0,  // 18: leo.goose.example.query.v1.EnumQueryRequest.list_status:type_name -> leo.goose.example.query.v1.EnumQueryRequest.Status
	1,  // 19: leo.goose.example.query.v1.BoolQuery.BoolQuery:input_type -> leo.goose.example.query.v1.BoolQueryRequest
	2,  // 20: leo.goose.example.query.v1.Int32Query.Int32Query:input_type -> leo.goose.example.query.v1.Int32QueryRequest
	3,  // 21: leo.goose.example.query.v1.Int64Query.Int64Query:input_type -> leo.goose.example.query.v1.Int64QueryRequest
	4,  // 22: leo.goose.example.query.v1.Uint32Query.Uint32Query:input_type -> leo.goose.example.query.v1.Uint32QueryRequest
	5,  // 23: leo.goose.example.query.v1.Uint64Query.Uint64Query:input_type -> leo.goose.example.query.v1.Uint64QueryRequest
	6,  // 24: leo.goose.example.query.v1.FloatQuery.FloatQuery:input_type -> leo.goose.example.query.v1.FloatQueryRequest
	7,  // 25: leo.goose.example.query.v1.DoubleQuery.DoubleQuery:input_type -> leo.goose.example.query.v1.DoubleQueryRequest
	8,  // 26: leo.goose.example.query.v1.StringQuery.StringQuery:input_type -> leo.goose.example.query.v1.StringQueryRequest
	9,  // 27: leo.goose.example.query.v1.EnumQuery.EnumQuery:input_type -> leo.goose.example.query.v1.EnumQueryRequest
	18, // 28: leo.goose.example.query.v1.BoolQuery.BoolQuery:output_type -> google.api.HttpBody
	18, // 29: leo.goose.example.query.v1.Int32Query.Int32Query:output_type -> google.api.HttpBody
	18, // 30: leo.goose.example.query.v1.Int64Query.Int64Query:output_type -> google.api.HttpBody
	18, // 31: leo.goose.example.query.v1.Uint32Query.Uint32Query:output_type -> google.api.HttpBody
	18, // 32: leo.goose.example.query.v1.Uint64Query.Uint64Query:output_type -> google.api.HttpBody
	18, // 33: leo.goose.example.query.v1.FloatQuery.FloatQuery:output_type -> google.api.HttpBody
	18, // 34: leo.goose.example.query.v1.DoubleQuery.DoubleQuery:output_type -> google.api.HttpBody
	18, // 35: leo.goose.example.query.v1.StringQuery.StringQuery:output_type -> google.api.HttpBody
	18, // 36: leo.goose.example.query.v1.EnumQuery.EnumQuery:output_type -> google.api.HttpBody
	28, // [28:37] is the sub-list for method output_type
	19, // [19:28] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_example_query_query_proto_init() }
func file_example_query_query_proto_init() {
	if File_example_query_query_proto != nil {
		return
	}
	file_example_query_query_proto_msgTypes[0].OneofWrappers = []any{}
	file_example_query_query_proto_msgTypes[1].OneofWrappers = []any{}
	file_example_query_query_proto_msgTypes[2].OneofWrappers = []any{}
	file_example_query_query_proto_msgTypes[3].OneofWrappers = []any{}
	file_example_query_query_proto_msgTypes[4].OneofWrappers = []any{}
	file_example_query_query_proto_msgTypes[5].OneofWrappers = []any{}
	file_example_query_query_proto_msgTypes[6].OneofWrappers = []any{}
	file_example_query_query_proto_msgTypes[7].OneofWrappers = []any{}
	file_example_query_query_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_query_query_proto_rawDesc), len(file_example_query_query_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   9,
		},
		GoTypes:           file_example_query_query_proto_goTypes,
		DependencyIndexes: file_example_query_query_proto_depIdxs,
		EnumInfos:         file_example_query_query_proto_enumTypes,
		MessageInfos:      file_example_query_query_proto_msgTypes,
	}.Build()
	File_example_query_query_proto = out.File
	file_example_query_query_proto_goTypes = nil
	file_example_query_query_proto_depIdxs = nil
}
