package ws

import (
	"context"
	"errors"
	"io"
	"reflect"

	"github.com/coder/websocket"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"
)

// ClientStream defines the client-side behavior of a streaming RPC.
//
// All errors returned from ClientStream methods are compatible with the
// status package.
type ClientStream interface {
	// Context returns the context for this stream.
	//
	// It should not be called until after RecvMsg has returned. Once
	// called, subsequent client-side retries are disabled.
	Context() context.Context
	// CloseSend closes the send direction of the stream. This method always
	// returns a nil error. The status of the stream may be discovered using
	// RecvMsg. It is also not safe to call CloseSend concurrently with SendMsg.
	CloseSend() error
	// SendMsg is generally called by generated code. On error, SendMsg aborts
	// the stream. If the error was generated by the client, the status is
	// returned directly; otherwise, io.EOF is returned and the status of
	// the stream may be discovered using RecvMsg. For unary or server-streaming
	// RPCs (StreamDesc.ClientStreams is false), a nil error is returned
	// unconditionally.
	//
	// SendMsg blocks until:
	//   - There is sufficient flow control to schedule m with the transport, or
	//   - The stream is done, or
	//   - The stream breaks.
	//
	// SendMsg does not wait until the message is received by the server. An
	// untimely stream closure may result in lost messages. To ensure delivery,
	// users should ensure the RPC completed successfully using RecvMsg.
	//
	// It is safe to have a goroutine calling SendMsg and another goroutine
	// calling RecvMsg on the same stream at the same time, but it is not safe
	// to call SendMsg on the same stream in different goroutines. It is also
	// not safe to call CloseSend concurrently with SendMsg.
	//
	// It is not safe to modify the message after calling SendMsg. Tracing
	// libraries and stats handlers may use the message lazily.
	SendMsg(m proto.Message) error
	// RecvMsg blocks until it receives a message into m or the stream is
	// done. It returns io.EOF when the stream completes successfully. On
	// any other error, the stream is aborted and the error contains the RPC
	// status.
	//
	// It is safe to have a goroutine calling SendMsg and another goroutine
	// calling RecvMsg on the same stream at the same time, but it is not
	// safe to call RecvMsg on the same stream in different goroutines.
	RecvMsg(m proto.Message) error
}

// Compile-time check: clientStream implements the ClientStream interface.
var _ ClientStream = (*clientStream)(nil)

// clientStream is the base struct for all client-side stream stubs.
// It wraps a *Conn and uses protojson for SendMsg/RecvMsg.
type clientStream struct {
	conn             *Conn
	ctx              context.Context
	cancel           context.CancelFunc
	marshalOptions   protojson.MarshalOptions
	unmarshalOptions protojson.UnmarshalOptions
}

// NewClientStream creates a base client stream wrapping an established Conn.
// The caller is responsible for dialing the WebSocket and calling conn.Start()
// before passing the Conn here. The cancel function is called when CloseSend
// is invoked or the stream is otherwise torn down.
func NewClientStream(ctx context.Context, conn *Conn, marshalOpts protojson.MarshalOptions, unmarshalOpts protojson.UnmarshalOptions) *clientStream {
	streamCtx, cancel := context.WithCancel(ctx)
	// Start the conn with context.Background so that cancelling streamCtx
	// (e.g. after CloseSend) does not prematurely close the WebSocket.
	// The connection is closed when the server sends its close frame.
	go conn.Start(context.Background())
	return &clientStream{
		conn:             conn,
		ctx:              streamCtx,
		cancel:           cancel,
		marshalOptions:   marshalOpts,
		unmarshalOptions: unmarshalOpts,
	}
}

// Context implements ClientStream.
func (s *clientStream) Context() context.Context {
	return s.ctx
}

// CloseSend closes the send direction of the stream.
// The read side remains open so the caller can still receive messages
// (e.g. the server's final response in client-streaming RPCs).
func (s *clientStream) CloseSend() error {
	s.conn.CloseSend()
	return nil
}

// SendMsg serializes m and enqueues it for sending.
func (s *clientStream) SendMsg(m proto.Message) error {
	data, err := s.marshalOptions.Marshal(m)
	if err != nil {
		return err
	}
	if !s.conn.Send(data) {
		return io.ErrClosedPipe
	}
	return nil
}

// RecvMsg reads a message from the connection and deserializes it into m.
// Returns io.EOF when the server closes the stream.
//
// An empty message (zero-length text frame) is interpreted as an end-of-stream
// (EOS) marker, since WebSocket does not support half-close at the transport level.
func (s *clientStream) RecvMsg(m proto.Message) error {
	data, err := s.conn.Read(s.ctx)
	if err != nil {
		if errors.Is(err, context.Canceled) {
			return err
		}
		if errors.Is(err, context.DeadlineExceeded) {
			return err
		}
		// Map websocket close to io.EOF, mirroring gRPC behavior.
		if websocket.CloseStatus(err) != -1 {
			return io.EOF
		}
		return err
	}
	// An empty message is the EOS marker sent by the peer's CloseSend.
	if len(data) == 0 {
		return io.EOF
	}
	return s.unmarshalOptions.Unmarshal(data, m)
}

// close tears down the stream.
func (s *clientStream) close() {
	s.conn.Close()
	s.cancel()
}

// ServerStream defines the server-side behavior of a streaming RPC.
//
// Errors returned from ServerStream methods are compatible with the status
// package.  However, the status code will often not match the RPC status as
// seen by the client application, and therefore, should not be relied upon for
// this purpose.
type ServerStream interface {
	// Context returns the context for this stream.
	Context() context.Context
	// CloseSend closes the send direction of the stream. This method
	// initiates a graceful close of the underlying WebSocket connection,
	// signaling to the client that no more messages will be sent.
	// It is not safe to call CloseSend concurrently with SendMsg.
	CloseSend() error
	// SendMsg sends a message. On error, SendMsg aborts the stream and the
	// error is returned directly.
	//
	// SendMsg blocks until:
	//   - There is sufficient flow control to schedule m with the transport, or
	//   - The stream is done, or
	//   - The stream breaks.
	//
	// SendMsg does not wait until the message is received by the client. An
	// untimely stream closure may result in lost messages.
	//
	// It is safe to have a goroutine calling SendMsg and another goroutine
	// calling RecvMsg on the same stream at the same time, but it is not safe
	// to call SendMsg on the same stream in different goroutines.
	//
	// It is not safe to modify the message after calling SendMsg. Tracing
	// libraries and stats handlers may use the message lazily.
	SendMsg(m proto.Message) error
	// RecvMsg blocks until it receives a message into m or the stream is
	// done. It returns io.EOF when the client has performed a CloseSend. On
	// any non-EOF error, the stream is aborted and the error contains the
	// RPC status.
	//
	// It is safe to have a goroutine calling SendMsg and another goroutine
	// calling RecvMsg on the same stream at the same time, but it is not
	// safe to call RecvMsg on the same stream in different goroutines.
	RecvMsg(m proto.Message) error
}

// Compile-time check: serverStream implements the ServerStream interface.
var _ ServerStream = (*serverStream)(nil)

// serverStream is the concrete implementation of the ServerStream interface
// defined in stream_interfaces.go. It wraps a *Conn and uses protojson for
// SendMsg/RecvMsg.
type serverStream struct {
	conn             *Conn
	ctx              context.Context
	marshalOptions   protojson.MarshalOptions
	unmarshalOptions protojson.UnmarshalOptions
}

// newServerStream creates a base server stream wrapping conn.
func NewServerStream(ctx context.Context, conn *Conn, marshalOpts protojson.MarshalOptions, unmarshalOpts protojson.UnmarshalOptions) *serverStream {
	return &serverStream{
		conn:             conn,
		ctx:              ctx,
		marshalOptions:   marshalOpts,
		unmarshalOptions: unmarshalOpts,
	}
}

// Context returns the stream's context.
func (s *serverStream) Context() context.Context { return s.ctx }

// CloseSend closes the send direction of the stream by draining pending
// writes and then closing the underlying WebSocket connection.
func (s *serverStream) CloseSend() error {
	s.conn.DrainAndClose()
	return nil
}

// SendMsg serializes m using protojson and enqueues it for writing via Conn.
func (s *serverStream) SendMsg(m proto.Message) error {
	data, err := s.marshalOptions.Marshal(m)
	if err != nil {
		return err
	}
	if !s.conn.Send(data) {
		return io.ErrClosedPipe
	}
	return nil
}

// RecvMsg reads a message from Conn and deserializes it into m using protojson.
// Returns io.EOF when the client closes the stream.
//
// An empty message (zero-length text frame) is interpreted as an end-of-stream
// (EOS) marker sent by the client's CloseSend, since WebSocket does not support
// half-close at the transport level.
func (s *serverStream) RecvMsg(m proto.Message) error {
	data, err := s.conn.Read(s.ctx)
	if err != nil {
		if errors.Is(err, context.Canceled) {
			return err
		}
		if errors.Is(err, context.DeadlineExceeded) {
			return err
		}
		// Any websocket-level close (normal closure, going away, etc.)
		// maps to io.EOF — this is how the server detects that the client
		// has finished sending (equivalent to gRPC CloseSend).
		if websocket.CloseStatus(err) != -1 {
			return io.EOF
		}
		return err
	}
	// An empty message is the EOS marker sent by the client's CloseSend.
	// It signals that no more messages will be sent from the client side.
	if len(data) == 0 {
		return io.EOF
	}
	return s.unmarshalOptions.Unmarshal(data, m)
}

// ClientStreamingClient represents the client side of a client-streaming (many
// requests, one response) RPC. It is generic over both the type of the request
// message stream and the type of the unary response message. It is used in
// generated code.
type ClientStreamingClient[Req proto.Message, Res proto.Message] interface {
	// Send sends a request message to the server.  The client may call Send
	// multiple times to send multiple messages to the server.  On error, Send
	// aborts the stream.  If the error was generated by the client, the status
	// is returned directly.  Otherwise, io.EOF is returned, and the status of
	// the stream may be discovered using CloseAndRecv().
	Send(Req) error

	// CloseAndRecv closes the request stream and waits for the server's
	// response.  This method must be called once and only once after sending
	// all request messages.  Any error returned is implemented by the status
	// package.
	CloseAndRecv() (Res, error)

	// ClientStream is embedded to provide Context and CloseSend
	// functionality.  No other methods in the ClientStream should be called
	// directly.
	ClientStream
}

// ClientStreamingServer represents the server side of a client-streaming (many
// requests, one response) RPC. It is generic over both the type of the request
// message stream and the type of the unary response message. It is used in
// generated code.
//
// To terminate the RPC, call SendAndClose and return nil from the method
// handler or do not call SendAndClose and return an error from the status
// package.
type ClientStreamingServer[Req proto.Message, Res proto.Message] interface {
	// Recv receives the next request message from the client.  The server may
	// repeatedly call Recv to read messages from the request stream.  If
	// io.EOF is returned, it indicates the client called CloseAndRecv on its
	// ClientStreamingClient.  Any other error indicates the stream was
	// terminated unexpectedly, and the handler method should return, as the
	// stream is no longer usable.
	Recv() (Req, error)

	// SendAndClose sends a single response message to the client and closes
	// the stream.  This method must be called once and only once after all
	// request messages have been processed.  Recv should not be called after
	// calling SendAndClose.
	SendAndClose(Res) error

	// ServerStream is embedded to provide Context and CloseSend
	// functionality.  No other methods in the ServerStream should
	// be called directly.
	ServerStream
}

// ServerStreamingClient represents the client side of a server-streaming (one
// request, many responses) RPC. It is generic over the type of the response
// message. It is used in generated code.
type ServerStreamingClient[Res proto.Message] interface {
	// Recv receives the next response message from the server. The client may
	// repeatedly call Recv to read messages from the response stream.  If
	// io.EOF is returned, the stream has terminated with an OK status.  Any
	// other error is compatible with the status package and indicates the
	// RPC's status code and message.
	Recv() (Res, error)

	// ClientStream is embedded to provide Context
	// functionality.  No other methods in the ClientStream should be called
	// directly.
	ClientStream
}

// ServerStreamingServer represents the server side of a server-streaming (one
// request, many responses) RPC. It is generic over the type of the response
// message. It is used in generated code.
//
// To terminate the response stream, return from the handler method and return
// an error from the status package, or use nil to indicate an OK status code.
type ServerStreamingServer[Res proto.Message] interface {
	// Send sends a response message to the client.  The server handler may
	// call Send multiple times to send multiple messages to the client.  An
	// error is returned if the stream was terminated unexpectedly, and the
	// handler method should return, as the stream is no longer usable.
	Send(Res) error

	// ServerStream is embedded to provide Context and CloseSend
	// functionality.  No other methods in the ServerStream should
	// be called directly.
	ServerStream
}

// BidiStreamingClient represents the client side of a bidirectional-streaming
// (many requests, many responses) RPC. It is generic over both the type of the
// request message stream and the type of the response message stream. It is
// used in generated code.
type BidiStreamingClient[Req proto.Message, Res proto.Message] interface {
	// Send sends a request message to the server.  The client may call Send
	// multiple times to send multiple messages to the server.  On error, Send
	// aborts the stream.  If the error was generated by the client, the status
	// is returned directly.  Otherwise, io.EOF is returned, and the status of
	// the stream may be discovered using Recv().
	Send(Req) error

	// Recv receives the next response message from the server. The client may
	// repeatedly call Recv to read messages from the response stream.  If
	// io.EOF is returned, the stream has terminated with an OK status.  Any
	// other error is compatible with the status package and indicates the
	// RPC's status code and message.
	Recv() (Res, error)

	// ClientStream is embedded to provide Context and CloseSend
	// functionality.  No other methods in the ClientStream should be
	// called directly.
	ClientStream
}

// BidiStreamingServer represents the server side of a bidirectional-streaming
// (many requests, many responses) RPC. It is generic over both the type of the
// request message stream and the type of the response message stream. It is
// used in generated code.
//
// To terminate the stream, return from the handler method and return
// an error from the status package, or use nil to indicate an OK status code.
type BidiStreamingServer[Req proto.Message, Res proto.Message] interface {
	// Recv receives the next request message from the client.  The server may
	// repeatedly call Recv to read messages from the request stream.  If
	// io.EOF is returned, it indicates the client called CloseSend on its
	// BidiStreamingClient.  Any other error indicates the stream was
	// terminated unexpectedly, and the handler method should return, as the
	// stream is no longer usable.
	Recv() (Req, error)

	// Send sends a response message to the client.  The server handler may
	// call Send multiple times to send multiple messages to the client.  An
	// error is returned if the stream was terminated unexpectedly, and the
	// handler method should return, as the stream is no longer usable.
	Send(Res) error

	// ServerStream is embedded to provide Context and CloseSend
	// functionality.  No other methods in the ServerStream should
	// be called directly.
	ServerStream
}

// newMessage creates a new zero-value instance of a proto.Message type.
// It handles both pointer type parameters (e.g. *pb.Msg) and value type
// parameters (e.g. pb.Msg) via reflection.
func newMessage[T proto.Message]() T {
	var zero T
	rt := reflect.TypeOf(zero)
	if rt.Kind() == reflect.Pointer {
		return reflect.New(rt.Elem()).Interface().(T)
	}
	return reflect.New(rt).Interface().(T)
}

// GenericClientStream implements the ServerStreamingClient, ClientStreamingClient,
// and BidiStreamingClient interfaces. It is used in generated code.
type GenericClientStream[Req proto.Message, Res proto.Message] struct {
	ClientStream
}

// NewGenericClientStream creates a new GenericClientStream wrapping the given
// ClientStream.
func NewGenericClientStream[Req proto.Message, Res proto.Message](cs ClientStream) *GenericClientStream[Req, Res] {
	return &GenericClientStream[Req, Res]{ClientStream: cs}
}

var (
	_ ServerStreamingClient[*anypb.Any]             = (*GenericClientStream[*anypb.Any, *anypb.Any])(nil)
	_ ClientStreamingClient[*anypb.Any, *anypb.Any] = (*GenericClientStream[*anypb.Any, *anypb.Any])(nil)
	_ BidiStreamingClient[*anypb.Any, *anypb.Any]   = (*GenericClientStream[*anypb.Any, *anypb.Any])(nil)
)

// Send pushes one message into the stream of requests to be consumed by the
// server. The type of message which can be sent is determined by the Req type
// parameter of the GenericClientStream receiver.
func (x *GenericClientStream[Req, Res]) Send(m Req) error {
	return x.ClientStream.SendMsg(m)
}

// Recv reads one message from the stream of responses generated by the server.
// The type of the message returned is determined by the Res type parameter
// of the GenericClientStream receiver.
func (x *GenericClientStream[Req, Res]) Recv() (Res, error) {
	m := newMessage[Res]()
	if err := x.ClientStream.RecvMsg(m); err != nil {
		var zero Res
		return zero, err
	}
	return m, nil
}

// CloseAndRecv closes the sending side of the stream, then receives the unary
// response from the server. The type of message which it returns is determined
// by the Res type parameter of the GenericClientStream receiver.
func (x *GenericClientStream[Req, Res]) CloseAndRecv() (Res, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		var zero Res
		return zero, err
	}
	m := newMessage[Res]()
	if err := x.ClientStream.RecvMsg(m); err != nil {
		var zero Res
		return zero, err
	}
	return m, nil
}

// GenericServerStream implements the ServerStreamingServer, ClientStreamingServer,
// and BidiStreamingServer interfaces. It is used in generated code.
type GenericServerStream[Req proto.Message, Res proto.Message] struct {
	ServerStream
}

// NewGenericServerStream creates a new GenericServerStream wrapping the given
// ServerStream.
func NewGenericServerStream[Req proto.Message, Res proto.Message](ss ServerStream) *GenericServerStream[Req, Res] {
	return &GenericServerStream[Req, Res]{ServerStream: ss}
}

var (
	_ ServerStreamingServer[*anypb.Any]             = (*GenericServerStream[*anypb.Any, *anypb.Any])(nil)
	_ ClientStreamingServer[*anypb.Any, *anypb.Any] = (*GenericServerStream[*anypb.Any, *anypb.Any])(nil)
	_ BidiStreamingServer[*anypb.Any, *anypb.Any]   = (*GenericServerStream[*anypb.Any, *anypb.Any])(nil)
)

// Send pushes one message into the stream of responses to be consumed by the
// client. The type of message which can be sent is determined by the Res
// type parameter of the serverStreamServer receiver.
func (x *GenericServerStream[Req, Res]) Send(m Res) error {
	return x.ServerStream.SendMsg(m)
}

// SendAndClose pushes the unary response to the client and closes the send
// direction of the stream. The type of message which can be sent is determined
// by the Res type parameter of the clientStreamServer receiver.
func (x *GenericServerStream[Req, Res]) SendAndClose(m Res) error {
	if err := x.ServerStream.SendMsg(m); err != nil {
		return err
	}
	return x.ServerStream.CloseSend()
}

// Recv reads one message from the stream of requests generated by the client.
// The type of the message returned is determined by the Req type parameter
// of the clientStreamServer receiver.
func (x *GenericServerStream[Req, Res]) Recv() (Req, error) {
	m := newMessage[Req]()
	if err := x.ServerStream.RecvMsg(m); err != nil {
		var zero Req
		return zero, err
	}
	return m, nil
}
